### ISSUE TITLE
"switch directory" UX doesn't resolve friendly directory names

### ISSUE THREAD

**Issue by wickste** [microsoft/vision-ai-developer-kit#124]
![image](https://user-images.githubusercontent.com/19159740/57880234-196eb000-77d3-11e9-8e7b-f450c4a3c66c.png)

**Comment by Devinwong** [comment]
still finding a proper way to retrieve directory friendly name information

**Comment by v-prsasa** [comment]
@Devinwong Any update on this?

**Comment by v-iskha** [comment]
Under consideration for future updates.
