### ISSUE TITLE
device should use a proper hostname and be configured to be reachable at <hostname>.local

### ISSUE THREAD

**Issue by veyalla** [microsoft/vision-ai-developer-kit#166]
The device doesn't broadcast a proper hostname. Internally it seems to have `qcs605-32`. It should also have a proper name like *aivisiondevkit*. 

Further for better user experience when using ssh or webview from local module, it should be reachable using aivisiondevkit.local 

See: https://www.howtogeek.com/167190/how-and-why-to-assign-the-.local-domain-to-your-raspberry-pi/

**Comment by jkubicka** [comment]
First half of this issue, host name, was fixed.

**Comment by v-prsasa** [comment]
@jkubicka An update on this?

**Comment by jkubicka** [comment]
@v-prsasa No update yet. Please follow up with Devin via email on when we can get this fixed in the next firmware version release.

**Comment by v-iskha** [comment]
Under consideration for future updates.
