### ISSUE TITLE
OOBE changing Wifi should trigger a deployment

### ISSUE THREAD

**Issue by ancaantochi** [microsoft/vision-ai-developer-kit#202]
After changing wifi setting cameraIP changes and webstreammodule should be redeployed so it takes the new value for env variable RTSP_IP

**Comment by Devinwong** [comment]
@AltekJimmyChang , please make sure the value of RTSP_IP in default deployment.json gets updated after the wifi is reconfigured. Then please trigger the deployment again.

**Comment by Devinwong** [comment]
we discussed further about this issue. If we only reconfigure WiFi but not sign into Azure, we are not able to set the deployment. A suggestion is to modify the webstream module such that it gets the IP address from the device itself on runtime, like rtsp_ip = utility.getWlanIp()

**Comment by Devinwong** [comment]
Will update the default deployment json from specifying wlan0 IP address to localhost, so that we don't need changing the RTSP_IP value when WiFi network changes.

**Comment by patgarr** [comment]
Fix for this was checked into FW v0.5280.
