### ISSUE TITLE
Sleep Timer / Auto shutdown

### ISSUE THREAD

**Issue by jkubicka** [microsoft/vision-ai-developer-kit#206]
Develop and implement sleep timer or auto shutdown (after x minutes) feature to conserve battery. 

Users have found that the battery life doesn't last long (~2 hours), so when they attempt to turn it on, it's usually dead and needs to be charged again.

**Comment by jkubicka** [comment]
Keeping open as future product enhancement.

**Comment by PuneetRahejaMS** [comment]
since the product is developer kit, the user can program/develop this feature (and hopefully share for others’ future use)
