### ISSUE TITLE
OODB issue

### ISSUE THREAD

**Issue by philipcaffeine** [microsoft/vision-ai-developer-kit#210]
Using the device as Access Point. When doing an initial setup, we found out that connecting to an IoT Hub using an existing IoT Edge connection string in the following screen didn’t work. It seems that the camera works properly (indicated by 3 green LEDs), but no video is displayed on the IP address listed:

Creating a new device entry using the provided code makes things working.

**Comment by jkubicka** [comment]
Hi @philipcaffeine Using an existing connection string only works if the device is a camera and the vision sample is deployed to the device.

**Comment by jkubicka** [comment]
Closing - please re-open if you're still having any issues.
