### ISSUE TITLE
Home directory in SSH remote login

### ISSUE THREAD

**Issue by philipcaffeine** [microsoft/vision-ai-developer-kit#211]
Also, when creating credentials for SSH remote login, it seems that for the user no home directory was created, not a big issue, but a bit rough. Also something seems wrong with the IoT Edge Runtime:

Doing the same, but instead of using an existing connection string, creating a new device using the supplied code from the device, it seems all to work.

**Comment by Devinwong** [comment]
Philip, could you elaborate on the second issue? I don't understand what issue it's about IoTEdge Runtime.
_Doing the same, but instead of using an existing connection string, creating a new device using the supplied code from the device, it seems all to work._

**Comment by jkubicka** [comment]
Hi @philipcaffeine could you provide more details?

**Comment by PuneetRahejaMS** [comment]
Closing. Kindly reopen if further support is needed.
