### ISSUE TITLE
Can I reconfigure the wifi via the shell? [Support Needed]

### ISSUE THREAD

**Issue by lokijota** [microsoft/vision-ai-developer-kit#212]
I've received the device recently and set it up for my home network. I've now brought it to work and want to use it with the corp wifi. Is there a way to reconfig the wifi w/out repeating the setup?

I've shell'ed into the device and tried doing it manually using the command line, but it doesn't seem to work, following instructions such as these (that work on my Pi's):

**For Wep or no password:**
https://askubuntu.com/questions/294257/connect-to-wifi-network-through-ubuntu-terminal

**For WPA:**
https://askubuntu.com/questions/138472/how-do-i-connect-to-a-wpa-wifi-network-using-the-command-line

Sorry for the newbie question.

**Comment by jkubicka** [comment]
Hi @lokijota is the device MAC address registered on https://openwifi/ ?

**Comment by jkubicka** [comment]
Hi @lokijota unfortunately, the only way to reconfigure Wi-Fi settings is via setup and pressing and holding the power button on the back for 5+ seconds until the device goes into SoftAP mode. Then Connect and reconfigure from there.

**Comment by lokijota** [comment]
I eventually gave up trying and went with the UI, it's just not very convenient, as I keep alternating between the office and home, and the process takes a while. If it were scriptable it'd probably be much faster and avoid the networking switching process. Isn't there any direct way of doing it in the shell, some configurations file? I mean, I assume the web UI is making some changes, right?

(regarding openwifi, yes, I did that before starting with attempt)

**Comment by jkubicka** [comment]
We haven't found any other way to do it. The OOBE / setup should only take a few minutes.

We'll make note to improve user experience for WiFi configuration.

**Comment by jkubicka** [comment]
If you do find a way to update WiFi settings via config file, please let us know.

**Comment by jkubicka** [comment]
WiFi configuration file isn't accessible for security reasons.

**Comment by lokijota** [comment]
It's like re-configuring Alexa every time I want to use it :p . Thanks anyway for the help, I'll try to find a way anyway.
