### ISSUE TITLE
shrink repo

### ISSUE THREAD

**Issue by SLdragon** [microsoft/vision-ai-developer-kit#213]
Hi, team, we found vision-ai-developer-kit repo is large, it takes about 700+M, clone this repo would take about 2~3 minutes. Can we shrink this repo?

![image](https://user-images.githubusercontent.com/5545529/62911765-20986080-bdb8-11e9-85b8-42ae46a4420c.png)

Some reference: 
https://stackoverflow.com/questions/5613345/how-to-shrink-the-git-folder

**Comment by PuneetRahejaMS** [comment]
just by design and haven’t seen issues since this was reported long ago
