### ISSUE TITLE
OOBE - creating a new IoT Edge should instruct not to use spaces

### ISSUE THREAD

**Issue by juniem** [microsoft/vision-ai-developer-kit#216]
During OOBE user can create a new IoT Edge device. There is no indication in UI that the IoT Edge device can't contain spaces. User is not able to continue if the device name has space on it, but the user has no idea why. 

Instructions should be added to next FW release.

![image](https://user-images.githubusercontent.com/46569137/63037144-551d2280-be73-11e9-9d34-bdbb473a486b.png)

**Comment by Devinwong** [comment]
@AltekJimmyChang, please add a check of a space in iotedge name. Now the error is not handled by UI.

**Comment by jkubicka** [comment]
@Devinwong  @AltekJimmyChang Any update on this bug?

**Comment by Devinwong** [comment]
This was fixed. And will be released with the coming firmware update

**Comment by jkubicka** [comment]
@Devinwong Thanks Devin.

We'll close this ticket once the update goes out.

**Comment by patgarr** [comment]
Fix for this was checked into FW v0.5280.
