### ISSUE TITLE
AiVisionDevKitGetStartedModule failed to build as docker image

### ISSUE THREAD

**Issue by Devinwong** [microsoft/vision-ai-developer-kit#232]
Build samples\official\ai-vision-devkit-get-started\deployment.template.json in VS Code

Step 13/15 : RUN pip install iotccsdk-0.1.0+dev.tar.gz
---> Running in f6ff1e0a85b3
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Processing ./iotccsdk-0.1.0+dev.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-93rs7xx2/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-93rs7xx2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-req-build-93rs7xx2/
    Complete output (1 lines):
    error in iotccsdk setup command: "values of 'package_data' dict" must be a list of strings (got 'logger.conf')
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

It's caused by the update of setuptools.
By commenting this line in Dockerfile.arm32v7, it worked again.
# RUN pip install --upgrade setuptools

**Comment by jkubicka** [comment]
@mmydland @initmahesh Hi there, any update on this one?

**Comment by initmahesh** [comment]
I was able to build from master recently thsi can be closed
