### ISSUE TITLE
Sorry - I am not sure how to run these commands.  I am running ADB.exe from the powershell but when I run this code I get errors.

### ISSUE THREAD

**Issue by TELEMEMORY** [microsoft/vision-ai-developer-kit#240]
No plug and play support. OOF - going back to school

**Comment by jkubicka** [comment]
Hi @TELEMEMORY is this in reference to ticket 239?

https://github.com/microsoft/vision-ai-developer-kit/issues/239

**Comment by jkubicka** [comment]
Resolving this one as duplicate, and resuming support in https://github.com/microsoft/vision-ai-developer-kit/issues/239
