### ISSUE TITLE
This link does not work - https://azure.github.io/Vision-AI-DevKit-Pages/docs/Wi-Fi_issues/

### ISSUE THREAD

**Issue by TELEMEMORY** [microsoft/vision-ai-developer-kit#241]
No working - https://azure.github.io/Vision-AI-DevKit-Pages/docs/Wi-Fi_issues/

**Comment by juniem** [comment]
Fixed this. The correct link is [https://azure.github.io/Vision-AI-DevKit-Pages/docs/wifi_issues/](https://azure.github.io/Vision-AI-DevKit-Pages/docs/wifi_issues/)

**Comment by TELEMEMORY** [comment]
Thanks

Sent from my iPhone

On Sep 17, 2019, at 2:20 PM, Jussi Niemelä <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #241<https://github.com/microsoft/vision-ai-developer-kit/issues/241>.
