### ISSUE TITLE
Device password reset - How do you do this?

### ISSUE THREAD

**Issue by TELEMEMORY** [microsoft/vision-ai-developer-kit#242]
It seems there is a wifi password that I cannot remember on the device.  I cannot connect to the device to try and update firmware.  Is there another way to connect to the device?  Via USB-C?  Other?

**Comment by juniem** [comment]
The default password should be on in a label on the bottom of the device. That should work unless you have changed it. The way to update (reflash) firmware is to do it using platform tools. https://azure.github.io/Vision-AI-DevKit-Pages/docs/platform_tools/. It should set the password back to the default one.

You can connect to the device using USB-C and platform tools. The provides you basically a Linux terminal that allows you to run command directly in the device.

**Comment by jkubicka** [comment]
Hi @TELEMEMORY Closing this issue. You can also find answers to your questions/issues on our Get Help page:

https://visionaidevkitsupport.azurewebsites.net/?q=device%20password
