### ISSUE TITLE
Native samples, toolchain, and/or BSP

### ISSUE THREAD

**Issue by bmount** [microsoft/vision-ai-developer-kit#243]
This is perhaps a meta feature request, escalated here from Gitter per discussion with @jkubicka. It would be great to have minimal examples of eg:

- compiling native code for the devkit and linking to runtime dependencies like SNPE
- reading directly from the camera (either opening a device file and issuing ioctls a la video4linux, or whatever low-level zero-copy API is available)
- (maybe) using docker for the above as needed if this is essential for some aspect of Azure

If this is afield of the design focus of this project (totally understandable!), just a link to or dump of the Yocto build rules that are mentioned at various points in the documentation would be enough to enable community work to this end.

**Comment by jkubicka** [comment]
Hi @bmount looking into this.

@patgarr any insight into this?

**Comment by jkubicka** [comment]
@bmount We have the Python SDK for the camera which allows you to do your own application in Python. That SDK enables custom apps using the camera APIs.  https://github.com/microsoft/vision-ai-developer-kit/tree/master/camera-sdk

The SNPE SDK is also available so if the custom app also wants to do a custom model conversion to SNPE that might be doable https://developer.qualcomm.com/software/qualcomm-neural-processing-sdk

This might help - these are the firmware update instructions:

https://azure.github.io/Vision-AI-DevKit-Pages/docs/Firmware/#updating-the-firmware
