### ISSUE TITLE
Please helpme device stopped working after first setup

### ISSUE THREAD

**Issue by VVillar** [microsoft/vision-ai-developer-kit#245]
Hello,
 
Please I need help. I configured my device Vision AI DevKit but when I reestarted I can not initiate again, the lights are Green but I cannot find the IP Adress I when I push the button for 5 seconds I cannot configure it again.
 
I ran the command:
adb shell cat /data/misc/wifi/hostapd_virtual.conf
 
and the output differs from the troubleshooting page:
Page:
https://azure.github.io/Vision-AI-DevKit-Pages/docs/wifi_issues/
 >   ctrl_interface=/var/run/hostapd
      >   interface=softap0
      >   #driver=nl80211
      >   #ieee80211d=1
      >   ieee80211n=1
      >   hw_mode=g<br/>
      >   country_code=US
      >   ssid=MSIoT_E72FA8
      >   macaddr_acl=0
      >   channel=0
      >   wpa=2
      --- >   wpa_passphrase=NhEtVE3D  ---
      >   wpa_key_mgmt=WPA-PSK
      >   #wpa_pairwise=CCMP
      >   rsn_pairwise=TKIP CCMP
      >   ht_capab=HT20 SHORT-GI-20
      >   wmm_enabled=1
      >   ignore_broadcast_ssid=0

 
In my device:
 C:\platform-tools>adb shell cat /data/misc/wifi/hostapd_virtual.conf
ctrl_interface=/var/run/hostapd
interface=softap0
#driver=nl80211
#ieee80211d=1
ieee80211n=1
hw_mode=g
country_code=US
ssid=ap99999
macaddr_acl=0
channel=0
wpa=2
wpa_passphrase=12345678
wpa_key_mgmt=WPA-PSK
#wpa_pairwise=CCMP
rsn_pairwise=TKIP CCMP
ht_capab=HT20 SHORT-GI-20
wmm_enabled=1
ignore_broadcast_ssid=0
 
When I look for the IP is blank:
 C:\platform-tools>adb shell ip -f inet addr show wlan0

<Nothing appears>

Please help me.
 
Victor Villar

**Comment by v-joveri** [comment]
Hi @VVillar   

Can you please try to press the power button for 12 seconds, this will reset the device to oobe again.

Regards
João Veríssimo

**Comment by jkubicka** [comment]
@VVillar We've seen this issue before, and currently investigating. Try pressing and holding the power button on the back of the device between 4 and 6 seconds. LEDs should start blinking red, going into the SoftAP mode and the device SSID will show up in your Wi-Fi tray.

Otherwise, the best option would be to execute a firmware update:

https://azure.github.io/Vision-AI-DevKit-Pages/docs/Firmware/#updating-the-firmware

**Comment by Devinwong** [comment]
@VVillar , when you saw a static green light, were you able the see the HDMI output with inference results? If yes, that meant the device IoTEdge was running in offline mode because somehow the internet was not connected.
If it couldn't connect to the configured AP profile, you can use the following command from _adb shell_.
**_connectap <SSID> <passphrase> -1_**
This command will try to connect to the SSID you specify but it won't save the profile.
If you want to reconfigure the WiFi and store the profile, please do as What Jan suggested to turn on SoftAP mode again by pressing the power button around 6 seconds. Then you will be able to scan the SSID from your workstation and reconfigure it.

**Comment by VVillar** [comment]
Hello, I download the firmware files, copied into the same adb folder (C:\platform-tools), tried executing a firmware update, but it failed, now the light is red all time and the PC doesn't recognize the devkit trough the usb port.

The messages that I received in the command prompt when I tried to upgrade the version double clicking FastbootUpgrade_v6_4.bat:
Rebooting to fastboot mode ('The greenlight changed to red)
Press any key when device driver ready… ('I pressed a key on my PC)
Check fastboot devices..
Device is not attached

**Comment by VVillar** [comment]
Hello @jkubicka , @Devinwong 

I tried the 3 advices, first tried to update firmware, the lights turned to red, then I pressed the power button and lighs turned on again, I tried with the command connectap -1 this is the result, don't know how to continue.

![image](https://user-images.githubusercontent.com/1483310/65505658-15991b80-dea0-11e9-907d-6f139cf3cb47.png)

Please help me.

**Comment by jkubicka** [comment]
@VVillar Device may not be charged, try charging for at least 2 hours and flash again. Were you able to set up the device after you flashed the device the first time?

**Comment by Devinwong** [comment]
@VVillar , sorry there was a typo. the command should be     connectap <SSID> <passphrase> -1
for example, these are the logs from my side.

/ # connectap ASUS_5G password -1
[Connect AP] SSID=ASUS_5G, key=password, Security=-1
wlan.ko exists!
kill wpa_supplicant!
killall: wifimonitor: no process killed
[Scan AP]
Successfully initialized wpa_supplicant
eap_proxy:eap_proxy_get_imsi: Not initialized

apssid:ASUS_5G
================================================
Find AP:e0:3f:49:f1:7c:dc       5785    -21     [WPA2-PSK-CCMP][ESS]    ASUS_5G
================================================
OK
[Connectap] AP Proto is WPA2 CCMP
kill wpa_supplicant!
Successfully initialized wpa_supplicant
eap_proxy:eap_proxy_get_imsi: Not initialized

udhcpc (v1.24.1) started
Setting IP address 0.0.0.0 on wlan0
Sending discover...
Sending discover...
Sending discover...
Sending select for 192.168.1.41...
Lease of 192.168.1.41 obtained, lease time 86400
Setting IP address 192.168.1.41 on wlan0
Deleting routers
route: SIOCDELRT: No such process
Adding router 192.168.1.1
Recreating /var/run/resolv.conf
 Adding DNS server 192.168.1.1
connect to ASUS_5G successfully!
find softap0

**Comment by Devinwong** [comment]
@VVillar  when you saw the ip address gone, could you try if you are still connecting to internet? for example adb shell ping 1.1.1.1

**Comment by VVillar** [comment]
> @VVillar Device may not be charged, try charging for at least 2 hours and flash again. Were you able to complete device setup after you flashed the first time?

Hello @jkubicka , yes I was able to complete the first setup, when I tried to update the firmware the battery was at 90%. But I couldn't do it.

**Comment by VVillar** [comment]
> @VVillar , sorry the GitHub markup language trimmed my original parameter.
> the command should be     connectap [SSID] [passphrase] -1
> for example, these are the logs from my side.
> / # connectap ASUS_5G password -1
> [Connect AP] SSID=ASUS_5G, key=password, Security=-1
> wlan.ko exists!
> kill wpa_supplicant!
> killall: wifimonitor: no process killed
> [Scan AP]
> Successfully initialized wpa_supplicant
> eap_proxy:eap_proxy_get_imsi: Not initialized
> apssid:ASUS_5G
> Find AP:e0:3f:49:f1:7c:dc       5785    -21     [WPA2-PSK-CCMP][ESS]    ASUS_5G
> OK
> [Connectap] AP Proto is WPA2 CCMP
> kill wpa_supplicant!
> Successfully initialized wpa_supplicant
> eap_proxy:eap_proxy_get_imsi: Not initialized
> udhcpc (v1.24.1) started
> Setting IP address 0.0.0.0 on wlan0
> Sending discover...
> Sending discover...
> Sending discover...
> Sending select for 192.168.1.41...
> Lease of 192.168.1.41 obtained, lease time 86400
> Setting IP address 192.168.1.41 on wlan0
> Deleting routers
> route: SIOCDELRT: No such process
> Adding router 192.168.1.1
> Recreating /var/run/resolv.conf
> Adding DNS server 192.168.1.1
> connect to ASUS_5G successfully!
> find softap0

Hello @Devinwong , this is the result of the command 
![image](https://user-images.githubusercontent.com/1483310/65641857-3a86af00-dfc4-11e9-9514-5735e22365b7.png)

**Comment by VVillar** [comment]
> adb shell ping 1.1.1.1

This is the result of that command 
![image](https://user-images.githubusercontent.com/1483310/65642658-39ef1800-dfc6-11e9-8efd-d693b687bef2.png)

When I type the command adb shell ifconfig wlan0
This is the result:
![image](https://user-images.githubusercontent.com/1483310/65642753-63a83f00-dfc6-11e9-828a-01375245f40e.png)

**Comment by jkubicka** [comment]
@VVillar It looks like you have the device working - can you check Azure Portal for your IoT Hub?

**Comment by VVillar** [comment]
> @VVillar It looks like you have the device working - can you check Azure Portal for your IoT Hub?

Hello @jkubicka I deleted the IoTHub expecting that can take me to reset the device, what can I do now that I dont have the IoT hub in Azure. Please help me.

**Comment by jkubicka** [comment]
@VVillar Create a new one in your Azure Portal, and then go through device setup again by holding the power button for 5-6 seconds, LEDs will blink red, and connect to the device in your Wi-Fi tray and proceed through the setup steps. In device setup, the new Hub should show up under the subscription screen.

https://azure.github.io/Vision-AI-DevKit-Pages/docs/quick_start/#connect-your-pc-to-the-cameras-wi-fi-access-point

**Comment by VVillar** [comment]
> @VVillar Create a new one in your Azure Portal, and then go through device setup again by holding the power button for 5-6 seconds, LEDs will blink red, and connect to the device in your Wi-Fi tray and proceed through the setup steps. In device setup, the new Hub should show up under the subscription screen.
> https://azure.github.io/Vision-AI-DevKit-Pages/docs/quick_start/#connect-your-pc-to-the-cameras-wi-fi-access-point

Hello @jkubicka when I push the button for 5-6 seconds the lights turn green again and I cant see the wifi ssid of the kit, so I cant configure it again. Is there any additional option to reset the device so I can configure again the device?
![image](https://user-images.githubusercontent.com/1483310/65814090-eb9f6c00-e1b3-11e9-9226-8204441332ee.png)

**Comment by VVillar** [comment]
Hello @jkubicka @Devinwong I reflashed the device using this link https://azure.github.io/Vision-AI-DevKit-Pages/docs/Recover_device/ , now I can see the network and I completed the setup process again successfully.

**Comment by jkubicka** [comment]
@VVillar Great to hear! We're close this ticket. Please let us know if you need help with anything else.

**Comment by V4A001** [comment]
Run in same issue here. After a couple of days I believe this software is quite buggy....

**Comment by V4A001** [comment]
I keep on running into this issue. I guess it occurs when no credentials to the Azure Container Registry is given..I have setup createOptions for both edgeAgent and edgeHub:

  "createOptions": {
                "HostConfig": {
                  "Dns": [
                    "1.1.1.1"
                  ],
                  "PortBindings": {
