### ISSUE TITLE
Yocto layer, OS sources

### ISSUE THREAD

**Issue by nicolaerosia** [microsoft/vision-ai-developer-kit#246]
Where can I get the Yocto layer to build the OS?
Are there are instructions available to flash my own build?

**Comment by jkubicka** [comment]
@nicolaerosia We have the Python SDK for the camera which allows you to do your own application in Python. That SDK enables custom apps using the camera APIs. https://github.com/microsoft/vision-ai-developer-kit/tree/master/camera-sdk

The SNPE SDK is also available so if the custom app also wants to do a custom model conversion to SNPE that might be doable https://developer.qualcomm.com/software/qualcomm-neural-processing-sdk

This might help - these are the firmware update instructions with a link to the BSP but no source code:

https://azure.github.io/Vision-AI-DevKit-Pages/docs/Firmware/#updating-the-firmware

**Comment by nicolaerosia** [comment]
I've sent an email to `opencode@microsoft.com` regarding the GPL license violation.

**Comment by jkubicka** [comment]
@nicolaerosia thanks for bringing this to our attention and reaching out to our open source programs office. Microsoft takes the GPL very seriously.  I’ve been in touch with our open source team and I understand they should be reaching out shortly to help resolve the issue.

**Comment by nicolaerosia** [comment]
great

**Comment by nicolaerosia** [comment]
For those interested in being able to customize the OS, as of 2019.10.14, I would recommend you to stay away from this board since a) it contains proprietary bits from Qualcomm, b) the open source components/Yocto meta layers along with their version/git hash/etc are not listed
