### ISSUE TITLE
modules/AIVisionDevKitGetStartedModule/python_iotcc_sdk/README.md link doesn't work

### ISSUE THREAD

**Issue by VVillar** [microsoft/vision-ai-developer-kit#247]

**Comment by PuneetRahejaMS** [comment]
@VVillar Thank you for pointing it out. Let me look into it and I'll get back

**Comment by PuneetRahejaMS** [comment]
@VVillar can you let me know where exactly is the above path located? I could not find it in the Code section

**Comment by VVillar** [comment]
https://github.com/microsoft/vision-ai-developer-kit/tree/master/samples/official/ai-vision-devkit-get-started

![image](https://user-images.githubusercontent.com/1483310/65962319-c5393500-e42e-11e9-82c9-b4a0c8c17411.png)

**Comment by jkubicka** [comment]
Hi @juniem this link is broken, can we get fixed?

**Comment by jkubicka** [comment]
Updated link to:

https://github.com/microsoft/vision-ai-developer-kit/tree/master/camera-sdk
