### ISSUE TITLE
Unresolved import properties.py

### ISSUE THREAD

**Issue by HowardEdidin** [microsoft/vision-ai-developer-kit#248]
from iotccsdk import CameraClient

unresolved import 'iotccsdk'Python(unresolved-import)
Peek Problem

unresolved import 'iotccsdk'

**Comment by jkubicka** [comment]
@howardedidin can you provide more details on where you’re seeing this issue?

**Comment by HowardEdidin** [comment]
`Step 13/16 : RUN pip install iotccsdk-0.1.4.tar.gz
 ---> Running in 8f21cda6d9ee
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Processing ./iotccsdk-0.1.4.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-iaumhfyu/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-iaumhfyu/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-req-build-iaumhfyu/
    Complete output (1 lines):
    error in iotccsdk setup command: "values of 'package_data' dict" must be a list of strings (got 'logger.conf')
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
The command '/bin/sh -c pip install iotccsdk-0.1.4.tar.gz' returned a non-zero code: 1`

**Comment by jkubicka** [comment]
@HowardEdidin Please provide a link to the GitHub code that's causing this error.

**Comment by jkubicka** [comment]
The error may be caused by the update of setuptools.
In Dockerfile.arm32v7, try removing the following line and run again:

RUN pip install --upgrade setuptools

**Comment by HowardEdidin** [comment]
That solved the problem. I was able to build the image
