### ISSUE TITLE
Device reset using existing connection string doesn't work

### ISSUE THREAD

**Issue by juniem** [microsoft/vision-ai-developer-kit#249]
It's not possible to reset the device using existing connection string.

Repro steps:
-Set up the device normally
-Press power button for 5 seconds and set the device again to AP mode
-Log in to the device and run the OOBE again
-Select "reset the device" and "I have a connection string"
-Provide a different connection string than what device currently has. The device gets stuck in loading IoT Edge runtime. When looking at the connectiong string with adb it still shows the old connection string

**Comment by mimcco** [comment]
@Devinwong - I think this belongs to you.

**Comment by jkubicka** [comment]
Should be released with next firmware update.

**Comment by Devinwong** [comment]
I was not able to repro this issue.
Please check your work station is still connecting to the VAIDK Wi-Fi when it's downloading iotedge containers.

**Comment by jkubicka** [comment]
@juniem Closing issue, please re-open if you're able to repro or if still an issue.
