### ISSUE TITLE
CameraTaggingModule architecture

### ISSUE THREAD

**Issue by osoroshi** [microsoft/vision-ai-developer-kit#250]
Deployed camerataggingmodule:0.1.67-amd64 to device but get this error in logs

/ # iotedge logs CameraTaggingModule
standard_init_linux.go:207: exec user process caused "exec format error"

**Comment by PuneetRahejaMS** [comment]
@osoroshi can you share the link where this module is available.

**Comment by osoroshi** [comment]
https://github.com/microsoft/vision-ai-developer-kit/tree/master/samples/official/camera-tagging

Following the Deploy Container AMD64 instructions - all modules running except for 
CameraTaggingModule        **failed**           Failed (1) 44 seconds ago  aivisionreg.azurecr.io/camerataggingmodule:0.0.62-amd64
edgeHub                    running          Up 2 hours                 mcr.microsoft.com/azureiotedge-hub:1.0
azureblobstorageoniotedge  running          Up 2 hours                 mcr.microsoft.com/azure-blob-storage:latest
VisionSampleModule         running          Up 2 hours                 mcr.microsoft.com/aivision/visionsamplemodule:1.1.3-arm32v7
edgeAgent                  running          Up 2 hours                 mcr.microsoft.com/azureiotedge-agent:1.0

**Comment by PuneetRahejaMS** [comment]
@osoroshi At a quick glance it looks like you may have accidentally build the module for amd64 and not arm32v7. 
If that is the case, you can update the build target architecture by clicking on amd64 at the bottom of the Visual Studio Code window and then at the top select the appropriate architecture (arm32v7). Pls refer to the screenshots below.

![2](https://user-images.githubusercontent.com/47889599/66743354-57155900-ee97-11e9-91aa-caf3d34ffd55.png)
![1](https://user-images.githubusercontent.com/47889599/66743355-57155900-ee97-11e9-8f74-6d2d93bd8553.png)

**Comment by PuneetRahejaMS** [comment]
Hope the information shared resolved your concern. we are closing this case. Please open a new one if further support is required.

**Comment by osoroshi** [comment]
Thanks switching to arm32 resolved the issue
