### ISSUE TITLE
Collecting Images from Camera using python command causes modules to stop working.

### ISSUE THREAD

**Issue by drcrook1** [microsoft/vision-ai-developer-kit#258]
Get a module running, then try to collect images.  It cuts the HDMI to a grey screen.  Trying to restart the device causes 1 single blinking green light.  Not sure how to restart the device to see how to fix this issue.

**Comment by jkubicka** [comment]
@drcrook1 Looking into this - will get back to you with more info. Thanks.

**Comment by PuneetRahejaMS** [comment]
@drcrook1 Can you share more information like error logs, screenshots etc which will help investigate further.

**Comment by mimcco** [comment]
@drcrook1 here is how to reboot the device https://visionaidevkitsupport.azurewebsites.net/?q=reboot

Let us know if rebooting resolves this issue. Thanks.

**Comment by jkubicka** [comment]
@drcrook1 Closing issue, please re-open if issue still exists.

**Comment by PuneetRahejaMS** [comment]
@drcrook1 Were you able to resolve your issue. Do update us so that we can investigate further.
