### ISSUE TITLE
Wi-Fi Reconfiguration Experience

### ISSUE THREAD

**Issue by jkubicka** [microsoft/vision-ai-developer-kit#259]
Once the device has been initially setup, the device will only connect to the original Wi-Fi network connected in the first device setup experience.

Current manual workaround is via adb commands: 
http://visionaidevkitsupport-test.azurewebsites.net/?q=switch%20wifi

Need more user-friendly experience to switch device Wi-Fi networks:
-Pop-up alert message that original network is not available, and new networks are available - should connect?

**Comment by jkubicka** [comment]
Should be included in next firmware release.

**Comment by v-iskha** [comment]
Under consideration for future updates.
