### ISSUE TITLE
SSH Tool Instructions improvements needed

### ISSUE THREAD

**Issue by jkubicka** [microsoft/vision-ai-developer-kit#260]
Current SSH instructions to connect/manage device:

https://azure.github.io/Vision-AI-DevKit-Pages/docs/SSH/

Suggested updates:

- Screenshots
- More accessible / easier to find on website
- Example of SSH use case - with list of sample commands

**Comment by V4A001** [comment]
Yep! In particular for non-linux developers which are spoiled with Visual Studio en .NET :-).

**Comment by v-iskha** [comment]
Under consideration for future updates.
