### ISSUE TITLE
OOBE Wi-Fi Setup Connection

### ISSUE THREAD

**Issue by jkubicka** [microsoft/vision-ai-developer-kit#266]
We encountered a new bug last week. Specific to firmware v0.5280.
In OOBE, we have a step to check if internet is good or not by pinging www.bing.com.
It would reply since last year but seems recently stop replying to the ping request.
You can try with your local PC cmd prompt with command ping www.bing.com
So user now will see the “internet seems bad” error message on OOBE because the ping failure (even though the device has connected to WiFi and internet).
Now as a workaround, user can still click on next to get the Device Code for Azure sign in.

**Comment by jkubicka** [comment]
Hi @Devinwong has this bug fix been checked into v0.5330?

**Comment by Devinwong** [comment]
yes. this is fixed at 0.5330

**Comment by jkubicka** [comment]
Closing per Devin's comment. Fixed in 0.5330
