### ISSUE TITLE
Update the security daemon?

### ISSUE THREAD

**Issue by V4A001** [microsoft/vision-ai-developer-kit#269]
https://docs.microsoft.com/en-us/azure/iot-edge/how-to-update-iot-edge
Where to run these commands? The bash asks unixuser..pwd and I do not know pwd.

apt-get update
apt-get install libiothsm iotedge

**Comment by PuneetRahejaMS** [comment]
@V4A001 Can you share more details on where exactly it's asking for a pwd.

**Comment by V4A001** [comment]
Can you point me to where the vision kit security demon is updated from a WIndows Machine? I get the security question on either the shell of the adb shell and on the terminal session for the virtual environment.

**Comment by jkubicka** [comment]
@V4A001 It's an ARM32 camera, please use the following doc:

https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-linux

**Comment by jkubicka** [comment]
@V4A001 Closing issue. Please re-open if still an issue.
