### ISSUE TITLE
Request to use Moby containers instead of Yocto docker containers for production usage

### ISSUE THREAD

**Issue by V4A001** [microsoft/vision-ai-developer-kit#271]
As a user I want finally run my developments on Azure IoT edge and customer might require professional support so that they get help from Microsoft.

However, I understand that this devkit is created in Yocto docker containers whereas Microsoft runs Moby containers in IoT Edge in production. Is there a roadmap to port Qualcomm image to Moby?

https://docs.microsoft.com/bs-latn-ba/azure/iot-edge/support

**Comment by jkubicka** [comment]
@V4A001 The AI Dev Kit does use Moby, which is baked into the Yocto OS shipped on the AI Vision dev kit. So yes, Microsoft officially supports the docker engine running on the AI Vision Dev Kit.
