### ISSUE TITLE
Change the style of bounding box display on the monitor

### ISSUE THREAD

**Issue by wei-juncheng** [microsoft/vision-ai-developer-kit#272]
Hi,
By default, the color of bounding box which the devices are showing is white.
Can I change the color of bounding box when the device detect something.
For example, if it detect the worker on the workplace and he doesn't wear a hard hat, I want to show red bounding box on his face.

**Comment by PuneetRahejaMS** [comment]
@jkubicka Would you know this?

**Comment by jkubicka** [comment]
@wei-juncheng This would be possible on a module built from scratch on the QMMF webserver/API, which is much more robust. But not on the current default module - which is built on the IPC webserver/API. Thus, the bounding box color on the current default module can only be white.

**Comment by jkubicka** [comment]
@wei-juncheng Here's documentation on how to build on QMMF:

https://source.codeaurora.org/quic/la/platform/vendor/qcom-opensource/qmmf-sdk
https://source.codeaurora.org/quic/la/platform/vendor/qcom-opensource/qmmf-webserver

**Comment by wei-juncheng** [comment]
Thanks a lot !
