### ISSUE TITLE
How to debug on dev box and how to debug on device?

### ISSUE THREAD

**Issue by V4A001** [microsoft/vision-ai-developer-kit#273]
Can you provide some links to how to develop and run a debugger on a local dev box with emulator? 
Same question for debugging locally on the device.

**Comment by PuneetRahejaMS** [comment]
@V4A001 Please allow me some time to get more details on your concern

**Comment by PuneetRahejaMS** [comment]
Hello @V4A001 Can you kindly share more details about the Dev box mentioned in your query.

**Comment by V4A001** [comment]
I will check those. I mean debugging on a dev-box without having a device and step into a docker module. It is not like windows .ce with platform builder and you just start up the debugger and it automatically connects.

**Comment by PuneetRahejaMS** [comment]
@V4A001 We didn’t provide a debugger on from a dev box as it won’t be able to access Qualcomm’s SNPE and hardware acceleration.
Qualcomm didn’t provide such an emulator as well.

**Comment by V4A001** [comment]
I am fighting with this already quite a time. Help appreciated to get pytest running and debugger. Python is really a pain in setting up properly with respect to a .NET library.

https://docs.pytest.org/en/latest/goodpractices.html#test-package-name

![image](https://user-images.githubusercontent.com/9630343/69870429-18552a00-12b0-11ea-86a8-469ffe68bac5.png)

**Comment by PuneetRahejaMS** [comment]
@V4A001 Looking at the screenshot, we cannot tell where your image_decoder module is. This error is just indicating that the module's path is invalid. This has nothing to do with DevKit.

**Comment by V4A001** [comment]
I fixed above. I added pytest to start with, but missed the __init__.py in the test framework.

I want to debug real-time the code on either my laptop or on the device and step through the code.

            while True:
                    try:
                        while camera_client.vam_running:                            
                            with camera_client.get_inferences() as results:
                                for result in results:
                                    last_time = print_inference(
                                        result, iot_hub_manager, last_time)

**Comment by V4A001** [comment]
I followed this article on a Windows instead Mac box:
https://devblogs.microsoft.com/iotdev/easily-build-and-debug-iot-edge-modules-on-your-remote-device-with-azure-iot-edge-for-vs-code-1-9-0/

I have created deployment files with debug and docker file:

RUN pip3 install --upgrade pip 
RUN pip install setuptools
RUN pip install ptvsd

main with:
# Debugging with Visual Studio Code on Edge Device
import ptvsd

ptvsd.enable_attach(('0.0.0.0',  5678))

and .env file:
"DOCKER_HOST"="ssh://useradmin@myip"

> (Inner Exception #0) Microsoft.Azure.Devices.Edge.Agent.Edgelet.EdgeletCommunicationException- Message:Error calling start module AIVisionDevKitGetStartedModule: Could not start module AIVisionDevKitGetStartedModule
        caused by: Could not start module AIVisionDevKitGetStartedModule
        caused by: failed to add interface veth5943327 to sandbox: error setting interface "veth5943327" IP to 172.18.0.4/16: cannot program address 172.18.0.4/16 in sandbox interface because it conflicts with existing route {Ifindex: 9 Dst: 172.18.0.0/16 Src: 172.18.0.1 Gw: <nil> Flags: [] Table: 254}, StatusCode:500, at:   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Version_2019_01_30.ModuleManagementHttpClient.HandleException(Exception exception, String operation) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2019_01_30/ModuleManagementHttpClient.cs:line 194
