### ISSUE TITLE
Rescan networks does not always list all network if you have about 8 ssid's

### ISSUE THREAD

**Issue by V4A001** [microsoft/vision-ai-developer-kit#274]
Just minor report: I needed to rescan 3 times to get my newly created ssid out of a list of 8 ssid's.

**Comment by PuneetRahejaMS** [comment]
@V4A001 We were unable to repro this. We tested it on the latest firmware v0.5330. There is no such limitation of 8 SSID's. 
Which firmware version are you using?

**Comment by V4A001** [comment]
Seems to be oke, was on version v0.5280_Perf

**Comment by PuneetRahejaMS** [comment]
@V4A001 Since this is no longer a repro, we are closing this issue.
