### ISSUE TITLE
#Model importing in camera

### ISSUE THREAD

**Issue by 0chandansharma** [microsoft/vision-ai-developer-kit#275]
Hi,

i have created keras_retinanet model weight file (output.h5),
i want to push my .h5 file (keras model) to the AI camera,

what i have tried 
>i have also tried to create my model using tensorflow (output.pb ) file
> after that i have converted my model form .pb to .dlc using qualcomm snpe 
>now i want to push this model in the altek camera but unable to do, can anyone help me with correct documentation.

**Comment by PuneetRahejaMS** [comment]
@DavidGrob-V-MS Can you help here.

**Comment by PuneetRahejaMS** [comment]
@0chandansharma you can use modelzipurl. but for a complete deployment, he will need to replace this model file to a vs code solution. build it as container, push to ACR and then deploy to iotedge

https://azure.github.io/Vision-AI-DevKit-Pages/docs/Tutorial-HOL_Using_the_VisionSample/

**Comment by PuneetRahejaMS** [comment]
@0chandansharma I hope the information shared resolved your concern. We are closing this as of now.  Please reopen if you need further assistance.

**Comment by 0chandansharma** [comment]
Thankyou for the response,

I already followed the documents,
> https://azure.github.io/Vision-AI-DevKit-Pages/docs/Deploy_Model_using_Module_Twin/
>https://azure.github.io/Vision-AI-DevKit-Pages/docs/Tutorial-HOL_Using_the_VisionSample/
>https://github.com/microsoft/vision-ai-developer-kit/blob/master/machine-learning-notebooks/04-Deploy-Trained-Model.ipynb


i am facing the issue :::: running status :backoff 

after importing my model in camera , and i am not getting output bounding boxes,

suggest me!

Thanks

**Comment by PuneetRahejaMS** [comment]
@0chandansharma 'Backoff' means the iotedge keeps restarting the vision module container but always encounters failure. To check what is happening, you can use command docker logs [container name] as well as docker logs edgeAgent. This will provide the logs from container starting to failure.

**Comment by 0chandansharma** [comment]
Thanks for response
Is there any model size restriction , for putting model in container , for altek camera ?
my model size is 22mb?
