### ISSUE TITLE
is there any c# or c++ SDK to connect the camera and get images frame by frame?

### ISSUE THREAD

**Issue by anguoyang** [microsoft/vision-ai-developer-kit#276]
is there any c# or c++ SDK to connect the camera and get images frame by frame? thank you

**Comment by PuneetRahejaMS** [comment]
@anguoyang It's not there. But new projects can be found here: https://azure.github.io/Vision-AI-DevKit-Pages/docs/projects/

**Comment by PuneetRahejaMS** [comment]
@anguoyang there is an API for capturing image https://azure.github.io/Vision-AI-DevKit-Pages/docs/train/ 
but it won't get images frame by frame. only when you send the API will it capture one frame

**Comment by V4A001** [comment]
@anguoyang I have same interest. I believe there is a project to tag images under the R&D samples.
