### ISSUE TITLE
Could not find a version that satisfies the requirement iothub-client==1.1.2.0 (from -r requirements.txt (line 24)) (from versions: none)

### ISSUE THREAD

**Issue by V4A001** [microsoft/vision-ai-developer-kit#277]
I am trying to make a deployable debuggable docker image.
With Python you get all your errors during run-time :-(...

So I got on my device by trying to run docker debug container:

/ # docker run b92fb640e210
Traceback (most recent call last):
  File "./main.py", line 17, in <module>
    from . properties import Properties
  File "/app/properties.py", line 4, in <module>
    from iotccsdk import CameraClient
ImportError: No module named 'iotccsdk'

So I added this one to my requirements.txt file.
Then the iothub-client, but seems something from 2017. How to get it ?

ERROR: Could not find a version that satisfies the requirement iothub-client==1.1.2.0 (from -r requirements.txt (line 24)) (from versions: none)
ERROR: No matching distribution found for iothub-client==1.1.2.0 (from -r requirements.txt (line 24))

**Comment by PuneetRahejaMS** [comment]
@V4A001 Let me check and get back to you.

**Comment by V4A001** [comment]
I am tyring to follow this: https://devblogs.microsoft.com/iotdev/easily-build-and-debug-iot-edge-modules-on-your-remote-device-with-azure-iot-edge-for-vs-code-1-9-0/

**Comment by Devinwong** [comment]
did you try with [this ](https://github.com/microsoft/vision-ai-developer-kit/blob/master/samples/official/ai-vision-devkit-get-started/modules/AIVisionDevKitGetStartedModule/requirements.txt)requirement.txt?

**Comment by PuneetRahejaMS** [comment]
@V4A001 Did you try the link shared by @Devinwong

**Comment by V4A001** [comment]
Fixed this bugs. Trying further to get a debugger on the docker image on the device.
