### ISSUE TITLE
Color of bounding box

### ISSUE THREAD

**Issue by djdtimit** [microsoft/vision-ai-developer-kit#278]
Hi,

is it possible to change the color of the bounding boxes or the color of the detected labels? White labels or bounding boxes are sometimes difficult to see. 

Best regards,
Tim

**Comment by PuneetRahejaMS** [comment]
@djdtimit This would be possible on a module built from scratch on the QMMF webserver/API, which is much more robust. But not on the current default module - which is built on the IPC webserver/API. Thus, the bounding box color on the current default module can only be white.

Below is the documentation on how to build on QMMF:

https://source.codeaurora.org/quic/la/platform/vendor/qcom-opensource/qmmf-sdk
https://source.codeaurora.org/quic/la/platform/vendor/qcom-opensource/qmmf-webserver

**Comment by jkubicka** [comment]
Closing issue.
