### ISSUE TITLE
Firmware Update fails

### ISSUE THREAD

**Issue by ericmcmc** [microsoft/vision-ai-developer-kit#279]
Hello,

I´m trying to update the firmware of the devkit to 0.5330_perf. I can see my device connected via adb devices but when I click in FastbootUpgrade_v6_5.bat like the instructions said the device become disconnected (red lights) and it fails. I also follow the instructions from here: https://azure.github.io/Vision-AI-DevKit-Pages/docs/Recover_device/#recover-vision-ai-dev-kit-hardware-after-a-failed-firmware-update to try to solve it but it fails too in adb reboot bootloader.

This is the error I get when I execute FastbootUpgrade_v6_5.bat

"Check adb device..."
"Device is not attached(X)"
"Fastboot upgrade fail(X)"
Press any key to continue . . .

There are other issue where it happens but you didn´t solve the firmware update part. My battery is more than 90%. https://github.com/microsoft/vision-ai-developer-kit/issues/245

Please could you help me with this?

Thanks

**Comment by PuneetRahejaMS** [comment]
@ericmcmc Can you press and release the power button for 12 seconds and then try flashing it again.

**Comment by PuneetRahejaMS** [comment]
@ericmcmc was this resolved?

**Comment by MarcoWirtl** [comment]
- Devices is attached

- Current Version (Shipping version) : v0.4940_Perf

- Is connected to WIFI and Azure IoT Hub

- All 4 Modules are on the camera (adb shell docker ps)

 

 

Running on Windows PC i copy the "FastbootUpgrade_v6_5.bat" + "VisionAIDevKit_InstallCheck.bat" File from the FW_UpgradeScript_Windows_v6_5 in the v0.5330_Perf Folder (where or what is the flat images folde in the PDF mentioned? / folder that contains the actual firmware files?)

--> see Screenshot 1
![Files](https://user-images.githubusercontent.com/58036042/71158516-6375b380-2244-11ea-897d-a177b0464de9.PNG)

 

In this case when i run the FastbootUpgrade.bat i get an error (../v0.5330_Perf/abl.elf is missing(X) --> Screenshot 2)
![Unbenannt](https://user-images.githubusercontent.com/58036042/71158565-76888380-2244-11ea-899a-9981ab50fd6c.PNG)


When i run the commands from Recover Vision AI Dev Kit hardware after a failed firmware update (https://azure.github.io/Vision-AI-DevKit-Pages/docs/Recover_device/#recover-vision-ai-dev-kit-hardware-after-a-failed-firmware-update) i get stucked by:

flastboot flash abl abl.elf
--> waiting for any device


Can anyone help?

**Comment by PuneetRahejaMS** [comment]
@ericmcmc Did you follow these instructions to update the firmware. https://azure.github.io/Vision-AI-DevKit-Pages/docs/Firmware/
Including the platform tools directory (containing the ADB and Fastboot utilities) in your computer’s path environment variable. Using the command  set path=%path%;<platform tools path> should resolve your issue.

**Comment by MarcoWirtl** [comment]
@PuneetRahejaMS 

What i have to change in the command? (set path=%path%;)

Like --> set path=C:\platform-tools; ???
Any example maybe?

Here a screenshot from my env. variables:

Like you see in "path" there are included the platform-tools.

![SysVariable](https://user-images.githubusercontent.com/58036042/71194585-888e1480-228c-11ea-8e4e-f4b43ea5fdf5.PNG)


If so than i did it right but got the issues presented above.

**Comment by V4A001** [comment]
> In this case when i run the FastbootUpgrade.bat i get an error (../v0.5330_Perf/abl.elf is missing(X) --> Screenshot 2)

There is an error in the .bat file.
Firmware upgrade to v0.5330_Perf --> needed to change fastboot *.bat file to point to this version

**Comment by MarcoWirtl** [comment]
@V4A001 

Could you specify where to change what? 

Maybe a Screenshot etc.?

I already tried a lot but stuck on this Point again and again.

Thanks

**Comment by V4A001** [comment]
Sure.

![image](https://user-images.githubusercontent.com/9630343/71323063-6fc17100-24cf-11ea-90da-77667195fd8c.png)

**Comment by MarcoWirtl** [comment]
@V4A001 

So i copied the .bat Files from windowsfolder  in the v0.5330 folder and changed the Script to:

fw_path = ./


But i sadly get the same error.

.elf file missing.

**Comment by V4A001** [comment]
Wrong. You need to include the path in which all the files are. If you start from scrath you download from the Qualcomm site the package. Unzip it. Then copy based on your os the .bat file to the root folder. So not in the folder itself. See image above. Then open the file FastbootUpgrade_v6_5.bat and modify the @SET fw_path=../v0.5330_Perf/ to the right version. In this case we want to upgrade to v0.5330_Perf.

If you have Microsoft Teams I can connect and we can do a screensharing (in German if you want :-)).

@echo "Check fastboot files..."
@SET fw_path=../v0.5330_Perf/
@SET filename=%fw_path%abl.elf
@IF NOT EXIST "%filename%" GOTO NOFILE_ERR 

![image](https://user-images.githubusercontent.com/9630343/71323508-4ce58b80-24d4-11ea-94e8-98c1f3d671bf.png)

**Comment by V4A001** [comment]
I had the error just now.
Just hardcode works. 
@echo "Check fastboot files..."
@SET fw_path=e:/v0.5330_Perf/
@SET filename=%fw_path%abl.elf
@IF NOT EXIST "%filename%" GOTO NOFILE_ERR

**Comment by MarcoWirtl** [comment]
Thanks i will try it tomorrow and let you know if it worked!

**Comment by MarcoWirtl** [comment]
@V4A001 

My folder structure:

![image](https://user-images.githubusercontent.com/58036042/71358400-13bb2300-2589-11ea-9172-bab25f12662d.png)


My .bat script:

![image](https://user-images.githubusercontent.com/58036042/71358438-377e6900-2589-11ea-9bc7-0080509f18cb.png)


I run the script as an admin:

1. USB Sound appears (disconnet) --> adb reboot bootloader
2. USB Sound appears again (connect) --> Press any key to continue
3. Output:

![image](https://user-images.githubusercontent.com/58036042/71358531-9b089680-2589-11ea-9ece-f22cf66153d3.png)


Info:
- When i start the .bat my device is connected to WIFI and Azure (green LED's)
- When i start the script it turns to solid red LED's and nothing else happen

- When i close the cmd window and type the command adb devices --> No devices attached

After rebooting the camera by clicking the button --> adb devices recognize my device again

**Comment by V4A001** [comment]
Hi, did you try again and succeed. To me it looks you are doing the right things. Can you open a second cmd prompt and run a ping next to the .bat file to see if you still have connectivity. It looks like connectivity has been lost.

@echo "Rebooting to fastboot mode"
adb reboot bootloader
@ping 127.0.0.1 -n 4 -w 1000 > nul
::@echo "Press any key when device driver ready..."
@pause

**Comment by V4A001** [comment]
It would be extremely helpful if you would point out how to modify code and how to debug it (easily) as used with CE.NET/ Visual Studio.

I came across this new feature in Visual Studio Code (https://code.visualstudio.com/docs/remote/containers). For the examples I get it to work..for this kit not. Help appreciated.

**Comment by V4A001** [comment]
"Check adb device..."
* daemon not running; starting now at tcp:5037
* daemon started successfully
"Check battery capacity..."
"Check fastboot files..."
"Rebooting to fastboot mode"

C:\WINDOWS\system32>adb reboot bootloader
Press any key to continue . . .
"Check fastboot devices..."
"Starting flashing image..."

C:\WINDOWS\system32>fastboot flash abl e:/v0.5330_Perf/abl.elf
Sending 'abl' (148 KB)                             OKAY [  0.009s]
Writing 'abl'                                      OKAY [  0.005s]
Finished. Total time: 0.053s

C:\WINDOWS\system32>fastboot flash boot e:/v0.5330_Perf/qcs605-boot.img
Sending 'boot_a' (36394 KB)                        OKAY [  1.058s]
Writing 'boot_a'                                   OKAY [  0.838s]
Finished. Total time: 2.358s

C:\WINDOWS\system32>fastboot flash system e:/v0.5330_Perf/qcs605-sysfs.ext4

**Comment by MarcoWirtl** [comment]
@V4A001 

![image](https://user-images.githubusercontent.com/58036042/71440663-3753aa00-26fe-11ea-8738-59a1633c606d.png)

After starting the .bat file ping command canceled.

Starting again says no advice.

**Comment by MarcoWirtl** [comment]
@V4A001 

 
![image](https://user-images.githubusercontent.com/58036042/71440764-be088700-26fe-11ea-90e0-99bfce2bc007.png)

After starting the .bat the pinc cmd canceled.

Starting at again says no advice....

**Comment by V4A001** [comment]
Maybe your fastboot is corrupted. Can you try to recover your device (take notice I am not the expert). I have multiple VisionKit devices so I 'sacrafized' one for this. With this manual you manually walk through the basic firmware upgrade files. It takes about 10 minutes to complete. After this you can try the fastboot again. Can also be your wifi is the issue by the way. But at least we know if you upgrade something on your device.

https://azure.github.io/Vision-AI-DevKit-Pages/docs/Recover_device/

E:\v0.5330_Perf>dir qcs60*
 Volume in drive E is DATA1
 Volume Serial Number is 9874-C879

 Directory of E:\v0.5330_Perf

25-11-2019  21:44        37.267.456 qcs605-boot.img
25-11-2019  21:44         5.275.796 qcs605-cache.ext4
25-11-2019  21:44         5.275.648 qcs605-cache_1.ext4
25-11-2019  21:44         4.358.304 qcs605-persist.ext4
25-11-2019  21:44         4.358.144 qcs605-persist_1.ext4
25-11-2019  21:45     1.994.085.988 qcs605-sysfs.ext4
25-11-2019  21:45       134.225.920 qcs605-sysfs_1.ext4
25-11-2019  21:45             8.192 qcs605-sysfs_10.ext4
25-11-2019  21:45       131.330.048 qcs605-sysfs_11.ext4
25-11-2019  21:45       132.120.576 qcs605-sysfs_12.ext4
25-11-2019  21:45             8.192 qcs605-sysfs_13.ext4
25-11-2019  21:45       131.330.048 qcs605-sysfs_14.ext4
25-11-2019  21:45       132.120.576 qcs605-sysfs_15.ext4
25-11-2019  21:45       132.120.576 qcs605-sysfs_16.ext4
25-11-2019  21:45       132.120.576 qcs605-sysfs_17.ext4
25-11-2019  21:45       132.120.576 qcs605-sysfs_18.ext4
25-11-2019  21:45       132.120.576 qcs605-sysfs_19.ext4
25-11-2019  21:45       133.435.392 qcs605-sysfs_2.ext4
25-11-2019  21:45        11.886.592 qcs605-sysfs_20.ext4
25-11-2019  21:45             8.192 qcs605-sysfs_21.ext4
25-11-2019  21:45             8.192 qcs605-sysfs_22.ext4
25-11-2019  21:45             8.192 qcs605-sysfs_23.ext4
25-11-2019  21:45             8.192 qcs605-sysfs_24.ext4
25-11-2019  21:45             8.192 qcs605-sysfs_25.ext4
25-11-2019  21:45             8.192 qcs605-sysfs_26.ext4
25-11-2019  21:45             8.192 qcs605-sysfs_27.ext4
25-11-2019  21:45             8.192 qcs605-sysfs_28.ext4
25-11-2019  21:45       132.120.576 qcs605-sysfs_3.ext4
25-11-2019  21:45             8.192 qcs605-sysfs_4.ext4
25-11-2019  21:45       131.330.048 qcs605-sysfs_5.ext4
25-11-2019  21:45       132.120.576 qcs605-sysfs_6.ext4
25-11-2019  21:45             8.192 qcs605-sysfs_7.ext4
25-11-2019  21:45       131.330.048 qcs605-sysfs_8.ext4
25-11-2019  21:45       132.120.576 qcs605-sysfs_9.ext4
25-11-2019  21:45         8.388.608 qcs605-systemrw.ext4
25-11-2019  21:45        91.933.256 qcs605-usrfs.ext4
25-11-2019  21:45        81.436.672 qcs605-usrfs_1.ext4
25-11-2019  21:45             8.192 qcs605-usrfs_10.ext4
25-11-2019  21:45             8.192 qcs605-usrfs_11.ext4
25-11-2019  21:45             8.192 qcs605-usrfs_12.ext4
25-11-2019  21:45             8.192 qcs605-usrfs_13.ext4
25-11-2019  21:45             8.192 qcs605-usrfs_14.ext4
25-11-2019  21:45             8.192 qcs605-usrfs_15.ext4
25-11-2019  21:45             8.192 qcs605-usrfs_16.ext4
25-11-2019  21:45             8.192 qcs605-usrfs_17.ext4
25-11-2019  21:45             8.192 qcs605-usrfs_18.ext4
25-11-2019  21:45             8.192 qcs605-usrfs_19.ext4
25-11-2019  21:45             8.192 qcs605-usrfs_2.ext4
25-11-2019  21:45             8.192 qcs605-usrfs_20.ext4
25-11-2019  21:45             8.192 qcs605-usrfs_21.ext4
25-11-2019  21:45             8.192 qcs605-usrfs_22.ext4
25-11-2019  21:45             8.192 qcs605-usrfs_23.ext4
25-11-2019  21:45             8.192 qcs605-usrfs_24.ext4
25-11-2019  21:45             8.192 qcs605-usrfs_25.ext4
25-11-2019  21:45             8.192 qcs605-usrfs_26.ext4
25-11-2019  21:45             8.192 qcs605-usrfs_27.ext4
25-11-2019  21:45             8.192 qcs605-usrfs_28.ext4
25-11-2019  21:45             8.192 qcs605-usrfs_29.ext4
25-11-2019  21:45             8.192 qcs605-usrfs_3.ext4
25-11-2019  21:45             8.192 qcs605-usrfs_30.ext4
25-11-2019  21:45             8.192 qcs605-usrfs_31.ext4
25-11-2019  21:45             8.192 qcs605-usrfs_32.ext4
25-11-2019  21:45             8.192 qcs605-usrfs_33.ext4
25-11-2019  21:45             8.192 qcs605-usrfs_34.ext4
25-11-2019  21:45             8.192 qcs605-usrfs_35.ext4
25-11-2019  21:45             8.192 qcs605-usrfs_36.ext4
25-11-2019  21:45             8.192 qcs605-usrfs_37.ext4
25-11-2019  21:45             8.192 qcs605-usrfs_38.ext4
25-11-2019  21:45             8.192 qcs605-usrfs_39.ext4
25-11-2019  21:45             8.192 qcs605-usrfs_4.ext4
25-11-2019  21:45             8.192 qcs605-usrfs_40.ext4
25-11-2019  21:45             8.192 qcs605-usrfs_41.ext4
25-11-2019  21:45             8.192 qcs605-usrfs_42.ext4
25-11-2019  21:45             8.192 qcs605-usrfs_43.ext4
25-11-2019  21:45             8.192 qcs605-usrfs_44.ext4
25-11-2019  21:45             8.192 qcs605-usrfs_45.ext4
25-11-2019  21:45        10.133.504 qcs605-usrfs_46.ext4
25-11-2019  21:45             8.192 qcs605-usrfs_5.ext4
25-11-2019  21:45             8.192 qcs605-usrfs_6.ext4
25-11-2019  21:45             8.192 qcs605-usrfs_7.ext4
25-11-2019  21:45             8.192 qcs605-usrfs_8.ext4
25-11-2019  21:45             8.192 qcs605-usrfs_9.ext4
25-11-2019  21:45         1.982.921 qcs605_le.log
              83 File(s)  4.238.908.329 bytes
               0 Dir(s)  420.655.550.464 bytes free

E:\v0.5330_Perf>adb reboot bootloader

E:\v0.5330_Perf>adb reboot bootloader
error: no devices/emulators found

E:\v0.5330_Perf>adb reboot bootloader
error: no devices/emulators found

E:\v0.5330_Perf>fastboot devices
f6b3d770        fastboot

E:\v0.5330_Perf>fastboot flash abl abl.elf
Sending 'abl' (148 KB)                             OKAY [  0.010s]
Writing 'abl'                                      OKAY [  0.006s]
Finished. Total time: 0.404s

E:\v0.5330_Perf>fastboot flash boot qcs605-boot.img
Sending 'boot_a' (36394 KB)                        OKAY [  1.101s]
Writing 'boot_a'                                   OKAY [  0.833s]
Finished. Total time: 2.705s

E:\v0.5330_Perf>fastboot flash system qcs605-sysfs.ext4
Sending sparse 'system_a' 1/13 (153598 KB)         OKAY [  5.487s]
Writing 'system_a'                                 OKAY [  0.000s]
Sending sparse 'system_a' 2/13 (153597 KB)         OKAY [  5.799s]
Writing 'system_a'                                 OKAY [  0.001s]
Sending sparse 'system_a' 3/13 (153598 KB)         OKAY [  5.799s]
Writing 'system_a'                                 OKAY [  0.000s]
Sending sparse 'system_a' 4/13 (153596 KB)         OKAY [  5.567s]
Writing 'system_a'                                 OKAY [  0.001s]
Sending sparse 'system_a' 5/13 (153597 KB)         OKAY [  6.004s]
Writing 'system_a'                                 OKAY [  0.001s]
Sending sparse 'system_a' 6/13 (136995 KB)         OKAY [  5.374s]
Writing 'system_a'                                 OKAY [  0.001s]
Sending sparse 'system_a' 7/13 (153597 KB)         OKAY [  5.751s]
Writing 'system_a'                                 OKAY [  0.000s]
Sending sparse 'system_a' 8/13 (150472 KB)         OKAY [  5.514s]
Writing 'system_a'                                 OKAY [  0.001s]
Sending sparse 'system_a' 9/13 (153597 KB)         OKAY [  5.864s]
Writing 'system_a'                                 OKAY [  0.000s]
Sending sparse 'system_a' 10/13 (153596 KB)        OKAY [  5.713s]
Writing 'system_a'                                 OKAY [  0.001s]
Sending sparse 'system_a' 11/13 (153597 KB)        OKAY [  6.854s]
Writing 'system_a'                                 OKAY [  0.001s]
Sending sparse 'system_a' 12/13 (136795 KB)        OKAY [  5.393s]
Writing 'system_a'                                 OKAY [  0.001s]
Sending sparse 'system_a' 13/13 (140710 KB)        OKAY [  5.965s]
Writing 'system_a'                                 OKAY [  0.001s]
Finished. Total time: 111.589s

E:\v0.5330_Perf>fastboot flash userdata qcs605-usrfs.ext4
Sending 'userdata' (89778 KB)                      OKAY [  2.703s]
Writing 'userdata'                                 OKAY [  0.001s]
Finished. Total time: 4.220s

E:\v0.5330_Perf>fastboot flash persist qcs605-persist.ext4
Sending 'persist' (4256 KB)                        OKAY [  0.133s]
Writing 'persist'                                  OKAY [  0.111s]
Finished. Total time: 0.755s

E:\v0.5330_Perf>fastboot flash cache qcs605-cache.ext4
Sending 'cache' (5152 KB)                          OKAY [  0.163s]
Writing 'cache'                                    OKAY [  0.001s]
Finished. Total time: 0.647s

E:\v0.5330_Perf>fastboot flash systemrw qcs605-systemrw.ext4
Sending 'systemrw' (8192 KB)                       OKAY [  0.250s]
Writing 'systemrw'                                 OKAY [  0.192s]
Finished. Total time: 0.952s

E:\v0.5330_Perf>fastboot reboot
Rebooting                                          OKAY [  0.000s]
Finished. Total time: 0.008s

E:\v0.5330_Perf>

now adb shell again. check version and that there are not docker images:
# docker images
# docker ps

The red lights are on all the time.

**Comment by MikeWilcoxMicrosoft** [comment]
> @V4A001
> Could you specify where to change what?
> Maybe a Screenshot etc.?
> I already tried a lot but stuck on this Point again and again.
> Thanks

Maybe this screen shot will help ?
![image](https://user-images.githubusercontent.com/57420850/71733753-ea638800-2e0f-11ea-89d8-e6e52804ba88.png)

**Comment by jkubicka** [comment]
This fastboot script issue should be fixed now - closing. Please re-open if issue still persists. Thanks.

**Comment by MarcoWirtl** [comment]
Updated my firmware.

My fastboot driver didn't work. 

Tried in on a friends mac --> updated
