### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by V4A001** [microsoft/vision-ai-developer-kit#280]
Could you please help how to modify and debug this code? I found this about remove container debugging and also some link about SSH connections. I am able to run the example and run a docker instance and debug it instantly with F5. How to get that done with this project?
https://code.visualstudio.com/docs/remote/containers

**Comment by PuneetRahejaMS** [comment]
@DavidGrob-V-MS Can you assist here?

**Comment by V4A001** [comment]
Help from VS Code team? 
https://github.com/microsoft/vscode-remote-release/issues/1951

**Comment by PuneetRahejaMS** [comment]
@V4A001 Checking if further assistance was required on this issue?

**Comment by PuneetRahejaMS** [comment]
@V4A001 Closing please reopen if further support is required

**Comment by V4A001** [comment]
Help still appreciated. Able to run container in VS code now. However, crashed on
    if ipc_provider is None:
        print("Create camera with no ipc_provider")
        return CameraClient.connect(
            ip_address=ip_address,
            username=username,
            password=password)

**Comment by V4A001** [comment]
HTTPConnectionPool(host='172.17.0.1', port=1080): Max retries exceeded with url: /login

**Comment by V4A001** [comment]
I believe it tries to connect to the python module that runs the camera, but cannot find it...hmmm.how to do that.
Create camera with no ipc_provider
2020-02-28 23:01:54,627 - iotccsdk - INFO - ipcprovider - connect:264 - API: http://172.17.0.1:1080/login data: {'username': 'admin', 'userpwd': 'admin'}

**Comment by PuneetRahejaMS** [comment]
@V4A001 It seems you are trying to connect to the IPC webserver which controls the SNPE (inference engine).
You can refer to these code snippets.
https://github.com/microsoft/vision-ai-developer-kit/blob/499b19b638135e731ed54217d9eca61492cb8382/samples/official/ai-vision-devkit-get-started/modules/AIVisionDevKitGetStartedModule/main.py#L35
Another suggestion is to connect to localhost(127.0.0.1) as a trial, if the user is going to connect to the IPC webserver from within the dev kit.
