### ISSUE TITLE
Can't get blinking Green leds to re run OOBE.

### ISSUE THREAD

**Issue by yguipsot** [microsoft/vision-ai-developer-kit#282]
I pressed the power button for 5 secs, pressed it for 12 secs too and the camera goes from static red to eventually static green; sometimes it goes from one red led to three static red leds.

I can't get the camera WiFi available again.

What am I doing wrong?

**Comment by PuneetRahejaMS** [comment]
@yguipsot The device should enter into SoftAP mode by pressing the power button for 5-6 seconds. BTW Three steady green LED lights mean the device is online, connected to IoT Hub, and ready for use.
What firmware version are you on?

**Comment by jkubicka** [comment]
@yguipsot Has this issue been resolved? If not, please re-open this ticket. Thanks.
