### ISSUE TITLE
Firmware-v0.5330_Perf-No way to download the modules (io_t_connect_string always empty)

### ISSUE THREAD

**Issue by jonmikeli** [microsoft/vision-ai-developer-kit#284]
Hi,

After many firmware updates, my last issue is related to the end of the setup and the downloads of the modules.

Once the wifi settings are over, the leds change from orange to green and they continue blinking.
I provide the connection string of the IoT Edge device through the setup portal (I have also tried to create the device through the portal) and this is the result:
 - leds continue blinking (in green)
 - no docker image is downloaded
 - no container is run with the local images
 - no deployment seems to be download
 - no connection happens with the IoT Hub

When I inspect the settings, it seems the connection string of the device is never set.
`adb shell cat /data/misc/websettings/setting.conf`

![image](https://user-images.githubusercontent.com/22737122/71617080-a5deaf00-2bb9-11ea-8e95-db0d2349fe48.png)

I have tested internet connectivity and it seems ok (pinging www.google.com).
Firmware version: v0.5330_Perf

A bug?
Any idea about how to solve this?

**Comment by PuneetRahejaMS** [comment]
@jonmikeli Can you try setting it manually and see if it works. We can investigate further after this initial test. Below is the process to update the string manually.

The ideal way is to update via device setup. Hold the power button for 5 seconds until blinking red LED's display, connect to the device AP, and then proceed through setup.

The device connection string is also stored on the device in the file ```/etc/iotedge/config.yaml```. To use vi editor and open/edit the file:
1. Open a command prompt as "Run as Administrator"
2. Command ```cd <platform tools path>```
3. Then use command ```adb shell```
4. Enter the command ```vi /etc/iotedge/config.yaml```

An alternative way to edit the device connection string, is to pull the ```/etc/iotedge/config.yaml``` file on the device and edit it on your local machine:
1. Open a command prompt as "Run as Administrator"
2. Command ```cd <platform tools path>```
3. Use the command ```adb pull /etc/iotedge/config.yaml``` to pull the file to the command directory on your local machine.
4. Open and edit the file locally with a text editor.
5. Use the command ```adb push config.yaml /etc/iotedge/config.yaml``` to push the updated file to the device.

**Comment by jonmikeli** [comment]
Hi @PuneetRahejaMS ,

Sure. No problem to test that.
`/etc/iotedge/config.yaml` is empty. The file exists but with 0 bytes in it.
It has only `read` permissions (it sounds strange because I expected to see `write` permissions too). Maybe the reason of the issue?

I have tried to change the settings manually in the `/data/misc/websettings/setting.conf` but it has no effect.

You will find below a screenshot of websettings.log.

![image](https://user-images.githubusercontent.com/22737122/71630319-9b94d300-2c02-11ea-8c92-77780f1cce18.png)

According to the logs, it seems the settings were done properly but nothing was written into the config.yaml file (buffer flushing issue? writing or permissions issue?).

The log file also shows that there are other issues when the process tried to delete different contents (cache folder, shm folder, edgeAgent, edgeHub).

If you want me to send you the whole log file, let me know.

**Comment by PuneetRahejaMS** [comment]
Hi @Devinwong is this something you are aware of?

**Comment by jonmikeli** [comment]
Hi @PuneetRahejaMS and @Devinwong,

A few updates ....
After a device reset and a new firmware update, everything works properly.

Two changes in the process:
 - everything has been executed as Administrator
 - I have monitored the network use through `adb shell ifconfig wlan0` (just to check that the images were downloaded). I do no think this point has had an impact but I mention it anyway.

**Comment by jonmikeli** [comment]
Not sure my changes have had an impact (I would not understand why because the settings are executed by another process). Once my PoCs with the kit over, I'll try to retest the process and if I reproduce the issue, I'll keep you posted. Thank you for your time.
