### ISSUE TITLE
Firmware update from 2680 to 5330 fails with three solid RED leds 

### ISSUE THREAD

**Issue by MikeWilcoxMicrosoft** [microsoft/vision-ai-developer-kit#288]
C:\Users\miwilcox\Documents\Vision Kit Microsoft\Tools\platform-tools_r29.0.5-windows\platform-tools>adb devices
List of devices attached
f6c3d974        device

C:\Users\miwilcox\Documents\Vision Kit Microsoft\Tools\platform-tools_r29.0.5-windows\platform-tools>adb shell cat /etc/version
v0.2680_Perf

C:\Users\miwilcox\Documents\Vision Kit Microsoft\Tools\platform-tools_r29.0.5-windows\platform-tools>FastbootUpgrade_v6_5.bat
"Check adb device..."
"Check battery capacity..."
"Check fastboot files..."
"Rebooting to fastboot mode"

C:\Users\miwilcox\Documents\Vision Kit Microsoft\Tools\platform-tools_r29.0.5-windows\platform-tools>adb reboot bootloader
Press any key to continue . . .
"Check fastboot devices..."
"Device is not attached(X)"
"Fastboot upgrade fail(X)"
Press any key to continue . . .

The camera now has three solid red leds which I believe indicates
"Device is powering on/off and/or performing system restore

How long should the camera sit on 'three solid red leds?'

**Comment by MikeWilcoxMicrosoft** [comment]
My bad, sorry team, I should have been patient.  
We might need to add a wait time after the 'adb reboot bootloader'  
I waited 2 minutes ( ie 120 seconds ) and the upgrade went forward..

Sample: 


C:\Users\miwilcox\Documents\Vision Kit Microsoft\Tools\platform-tools_r29.0.5-windows\platform-tools>FastbootUpgrade_v6_5.bat
"Check adb device..."
"Check battery capacity..."
"Check fastboot files..."
"Rebooting to fastboot mode"
C:\Users\miwilcox\Documents\Vision Kit Microsoft\Tools\platform-tools_r29.0.5-windows\platform-tools>adb reboot bootloader

>>> PLEASE WAIT 120 SECONDS BEFORE HTTING ANY KEY 

Press any key to continue . . .

**Comment by MikeWilcoxMicrosoft** [comment]
It appears that FastbootUpgrade_v6_5.bat indicates 'please wait 5 minutes are flash to check device'  yet FastbootUpgrade_v6_5.bat imediately calls  VisionAIDevKit_InstallCheck.bat which 1) wipes history which is annoying and 2) indicates the firmware upgrade failed ?  Maybe we should put in a delay in calling   VisionAIDevKit_InstallCheck.bat ?

**Comment by PuneetRahejaMS** [comment]
@MikeWilcoxMicrosoft Thanks for your feedback. Will share it with the team

**Comment by MikeWilcoxMicrosoft** [comment]
Glad to help... My 2020 resolution is the be 'patient'... Guess I need to work a little harder on that :)  
I appreciate you guys !

**Comment by jkubicka** [comment]
Closing - please re-open if issue still persists. Thanks.
