### ISSUE TITLE
Can't see webstream, rtsp stream with updated Firmware

### ISSUE THREAD

**Issue by MarcoWirtl** [microsoft/vision-ai-developer-kit#290]
Hallo everybody,

I updated my camera to the newest Firmware:

![image](https://user-images.githubusercontent.com/58036042/71955960-14d78b80-31ea-11ea-801d-dfb9960d4154.png)

- Configured it for my WLAN and Azure --> LED's solid green
- All 4 docker containers are running:

![image](https://user-images.githubusercontent.com/58036042/71956296-0a69c180-31eb-11ea-882d-f845be899ac3.png)

Is the command 'npm start' right???? 

- I'm in the same network like my camera but cant't ping the IP address

Any suggestions?

**Comment by PuneetRahejaMS** [comment]
@MarcoWirtl I hope you are not behind a Firewall which restricts ports. Can you also reboot the device once and check again.

**Comment by MarcoWirtl** [comment]
@PuneetRahejaMS 

Already rebooted device and setted up again...

Still no ping --> no stream

How to check the restricts ports if they are some?
