### ISSUE TITLE
ADB command documentation addition for when more than one ADB device is connected

### ISSUE THREAD

**Issue by SillyKeith** [microsoft/vision-ai-developer-kit#291]
I had 2 ADB devices connected and the ADB commands need to know which device should run the commands.

If you have more than one ADB device connected or receive the below error "_error: more than one device and emulator_" then use the _-s_ switch when specifying commands.

IE:  adb -s _<visionDevice>_ shell    
where _<visionDevice>_ = the device ID name listed from ADB devices.

**Comment by vasantha-Mindtree** [comment]
@SillyKeith : Thanks for the information. We will look into it and update shortly

**Comment by vasantha-Mindtree** [comment]
@juniem : There is a feedback regarding the current documentation. Can you kindly look into it.

**Comment by PuneetRahejaMS** [comment]
Closing this request as the docs have been updated.

https://azure.github.io/Vision-AI-DevKit-Pages/docs/platform_tools/
