### ISSUE TITLE
Bug | Module Identity Twin - Object of Interest

### ISSUE THREAD

**Issue by jkubicka** [microsoft/vision-ai-developer-kit#292]
Repro steps - when doing the following in Module Identity Twin:

- Updating the Object of Interest to a different object
- Clicking Save
- It doesn't save or work in the module

**Comment by jkubicka** [comment]
Hi @DavidGrob-V-MS Any update on ETA for this one?

**Comment by DavidGrob-V-MS** [comment]
Tested today and updating twin property from the Azure portal worked as expected with the current version of the module. I changed object of interest from "ALL" to "TV" (logging output from the camera below) . This functioned as expected and IoT hub messages were only sent for TV after the setting was updated. If the user is viewing the twin properties in the azure portal for a while before making and saving the change it may not update as expected. Have the user attempt making and saving the change twice in a row for testing.  

`Received twin callback
Received twin update: {'ObjectsOfInterest': '["TV"]', 'Codec': 'AVC/H.264', '$version': 5, 'FrameRate': 30, 'Bitrate': '1.5Mbps', 'VideoAnalyticsEnabled': True, 'TimeBetweenMessagesInSeconds': 12, 'ShowVideoOverlay': True, 'ModelZipUrl': '', 'HdmiDisplayActive': True, 'Resolution': '1080P', 'ShowVideoPreview': True, 'VideoOverlayConfig': 'inference'}
Send prop: {"Resolution": "1080P"}
Send prop: {"RtspVideoUrl": "rtsp://192.168.0.104:8900/live"}
Send prop: {"FrameRate": 30}
Send prop: {"RtspDataUrl": "rtsp://192.168.0.104:8902/live"}
Send prop: {"Bitrate": "1.5Mbps"}
Send prop: {"VideoOverlayConfig": "inference"}
Send prop: {"Codec": "AVC/H.264"}
Send prop: {"VideoAnalyticsEnabled": true}
Send prop: {"HdmiDisplayActive": true}
Send prop: {"ShowVideoOverlay": true}
Send prop: {"ShowVideoPreview": true}
Send prop: {"SupportedBitrates": "512Kbps | 768Kbps | 1Mbps | 1.5Mbps | 2Mbps | 3Mbps | 4Mbps | 6Mbps | 8Mbps | 10Mbps | 20Mbps"}
Send prop: {"SupportedConfigOverlayStyles": "text | inference"}
Send prop: {"SupportedEncodingTypes": "HEVC/H.265 | AVC/H.264"}
Send prop: {"SupportedFrameRates": "24 | 30"}
Send prop: {"SupportedResolutions": "4K | 1080P | 720P | 480P"}
Send prop: {"ModelZipUrl": ""}
Send prop: {"TimeBetweenMessagesInSeconds": 12}
Send prop: {"ObjectsOfInterest": "[\"TV\"]"}
Confirmation of 204 received for {"Resolution": "1080P"}.
Confirmation of 204 received for {"RtspVideoUrl": "rtsp://192.168.0.104:8900/live"}.
Confirmation of 204 received for {"FrameRate": 30}.
Confirmation of 204 received for {"RtspDataUrl": "rtsp://192.168.0.104:8902/live"}.
Confirmation of 204 received for {"Bitrate": "1.5Mbps"}.
Confirmation of 204 received for {"VideoOverlayConfig": "inference"}.
Confirmation of 204 received for {"Codec": "AVC/H.264"}.
Confirmation of 204 received for {"VideoAnalyticsEnabled": true}.
Confirmation of 204 received for {"HdmiDisplayActive": true}.
Confirmation of 204 received for {"ShowVideoOverlay": true}.
Confirmation of 204 received for {"ShowVideoPreview": true}.
Confirmation of 204 received for {"SupportedBitrates": "512Kbps | 768Kbps | 1Mbps | 1.5Mbps | 2Mbps | 3Mbps | 4Mbps | 6Mbps | 8Mbps | 10Mbps | 20Mbps"}.
Confirmation of 204 received for {"SupportedConfigOverlayStyles": "text | inference"}.
Confirmation of 204 received for {"SupportedEncodingTypes": "HEVC/H.265 | AVC/H.264"}.
Confirmation of 204 received for {"SupportedFrameRates": "24 | 30"}.
Confirmation of 204 received for {"SupportedResolutions": "4K | 1080P | 720P | 480P"}.
Confirmation of 204 received for {"ModelZipUrl": ""}.
Confirmation of 204 received for {"TimeBetweenMessagesInSeconds": 12}.
Confirmation of 204 received for {"ObjectsOfInterest": "[\"TV\"]"}.
send: b'\x89\x80\xac\xa5|G'`

**Comment by jkubicka** [comment]
Thanks @DavidGrob-V-MS Appreciate your help on this! :)

Hi @initmahesh David was unable to repro - are you still seeing this issue? If not, please let us know and we'll close this ticket. Thanks!

**Comment by jkubicka** [comment]
@PuneetRahejaMS Please close after 2 days if no response. Thanks.

**Comment by PuneetRahejaMS** [comment]
Closing since it's a repro. Reopen if required.

**Comment by PuneetRahejaMS** [comment]
Done
