### ISSUE TITLE
Camera needs to send userid and password in order to access the internet 

### ISSUE THREAD

**Issue by MikeWilcoxMicrosoft** [microsoft/vision-ai-developer-kit#296]
We need help w/ securing Internet access to & from the Visionai camera.

The camera will need to use a user id and password in order to auth to the customer firewall before access to the internet is allowed. I assume we can use a proxy server of some kind ?

**Comment by v-prsasa** [comment]
We are looking into it. We will update it shortly

**Comment by PuneetRahejaMS** [comment]
@MikeWilcoxMicrosoft, The dev kit doesn’t support entering credentials on a pop-up page.
If a proxy is preferred, you may need to whitelist the device (like Mac Address) in advance so that it can be connected automatically without entering credentials.

**Comment by PuneetRahejaMS** [comment]
Closing. Please contact us in case of further queries
