### ISSUE TITLE
How to add security to the ML zip file in BLOB 

### ISSUE THREAD

**Issue by MikeWilcoxMicrosoft** [microsoft/vision-ai-developer-kit#297]
Is there a way to add security to the ML BLOB zip file. We noticed the “public access level setting of ‘Private’ “ prevents download of the zip file to the camera?  Also is anonymous download is blocked how can we can we add a serivce id and secret so the camera can downloud the zip file in BLOB storage ?

**Comment by v-prsasa** [comment]
We are looking into it. We will update it shortly.

**Comment by PuneetRahejaMS** [comment]
Including @initmahesh for help.

**Comment by PuneetRahejaMS** [comment]
@MikeWilcoxMicrosoft There is a potential solution based on the below link.

https://stackoverflow.com/questions/42875787/download-all-blobs-files-locally-from-azure-container-using-python

**Comment by PuneetRahejaMS** [comment]
@MikeWilcoxMicrosoft Were you able to try the above solution?

**Comment by PuneetRahejaMS** [comment]
Closing, Kindly reopen if further support is required.
