### ISSUE TITLE
WiFi credentials are not persistent after rebooting the Vision AI Dev Kit

### ISSUE THREAD

**Issue by anilvpr** [microsoft/vision-ai-developer-kit#299]
1. Followed the instructions in step-3 of https://azure.github.io/Vision-AI-DevKit-Pages/docs/quick_start/ page.
2. WiFi Access Point credentials (SSID and Password) configured
3. Able to acess internet (Azure IoT) via this Access Point, everything is going well !!
4. Now power down the Dev Kit and power it up again
5. I expect the Dev Kit to automatically connect to the Access Point configured in the earlier steps. But it does not get connected !!
6. Only option is to press-n-hold the power button for 5 seconds to put the device to Configuration  mode and re-do the steps from 1 to 3

Why is the WiFi credentials not stored persistently across power cycles.

**Comment by v-prsasa** [comment]
We are looking into it.

**Comment by v-prsasa** [comment]
@anilvpr Can you try to reset your device once and verify.
You can follow this link- https://azure.github.io/Vision-AI-DevKit-Pages/docs/reset/

**Comment by brad302** [comment]
@anilvpr, are you on the latest firmware? Just a thought.

**Comment by anilvpr** [comment]
@v-prsasa Issue is resolved after device reset. Thank you.
