### ISSUE TITLE
requirments.txt outdated

### ISSUE THREAD

**Issue by herbzacz** [microsoft/vision-ai-developer-kit#300]
requirements.txt is outdated
some of the Azure packages have specific dependencies and let not run the whole script (research/VisionSample/MachineLearning/ssdsample)

**Comment by PuneetRahejaMS** [comment]
@herbzacz Thanks for pointing it out. Let me get back to you.

**Comment by DavidGrob-V-MS** [comment]
@herbzacz I was able to run through the existing requirements.txt with issue using the following to test: \GitHub\VisionFork\vision-ai-developer-kit\samples\research\VisionSample\MachineLearning\scripts>pip install --upgrade -r requirements.txt

Can you give us more details on which script is failing and at what error you are seeing?

**Comment by PuneetRahejaMS** [comment]
Closing. Kindly re-open if further support is needed.
