### ISSUE TITLE
RTSP using the liv link fails with VLC

### ISSUE THREAD

**Issue by namkedia** [microsoft/vision-ai-developer-kit#303]
Connection failed:
VLC could not connect to "--:8900".
Your input can't be opened:
VLC is unable to open the MRL 'rtsp://--:8900/live'. Check the log for details.

**Comment by MS-Nikunja** [comment]
We are looking into it. We will update it shortly.

**Comment by PuneetRahejaMS** [comment]
@namkedia I hope you followed https://azure.github.io/Vision-AI-DevKit-Pages/docs/RTSP_stream/
if not kindly go through it.

**Comment by PuneetRahejaMS** [comment]
@namkedia Was your issue resolved or needs further support. Kindly update

**Comment by PuneetRahejaMS** [comment]
Closing, Kindly re-open if further support is required.
