### ISSUE TITLE
Unable to connect camera from customer's private network

### ISSUE THREAD

**Issue by mwitman** [microsoft/vision-ai-developer-kit#304]
My customer is getting a "Your camera failed to download Azure IoT Edge runtime" error when attempting to connect the camera on their internal corp network using OOBE.  After connecting the camera to their internal AP they get an "Internet capability seems bad, try changing to another network" error.  Since the error is only a warning message after they click next it sits on the "downloading Azure IoT Edge runtime" screen for a long time and ends with the "Your camera failed to download Azure IoT Edge runtime" error.

Will the OOBE allow the user to get this far if there is no internet connectivity from the camera?  Their network has 2 DMZ firewalls and a Proxy Server between the camera and the public internet.  What ports need to be open outbound (assuming none inbound)? And does the camera require the following steps to configure the network proxy server? https://docs.microsoft.com/en-us/azure/iot-edge/how-to-configure-proxy-support.

Error message and network design screen shots attached.

[Sample Network Flow Diagram.pdf](https://github.com/microsoft/vision-ai-developer-kit/files/4221398/Sample.Network.Flow.Diagram.pdf)
[ErrorMessage.docx](https://github.com/microsoft/vision-ai-developer-kit/files/4221403/ErrorMessage.docx)

**Comment by MS-Nikunja** [comment]
@mwitman We are looking into it. Allow us some time to get back.

**Comment by PuneetRahejaMS** [comment]
@mwitman this can happen due to restrictions in corporate netwoks, 
Using ADB shell, can you run the below command and see if the device has picked up the IP 
Open a command prompt as "Run as Administrator"

Command cd <platform tools path>

Then use command adb shell ifconfig -a
then try to ping 
ping <device IP address>,

**Comment by PuneetRahejaMS** [comment]
@mwitman do you have any update for us. Was this resolved or needs further attention.

**Comment by PuneetRahejaMS** [comment]
Closing, Kindly re-open if further support is required.
