### ISSUE TITLE
Hardcoded Username/Password

### ISSUE THREAD

**Issue by toolboc** [microsoft/vision-ai-developer-kit#309]
There is a hardcoded Username/Password of `admin:admin` at the following:

https://github.com/microsoft/vision-ai-developer-kit/blob/a939db6e99c15c164e1500c765ff1e851cecd4d2/samples/official/camera-tagging/modules/CameraTaggingModule/CameraServerModule/scripts/mpeg4-stream.js#L174

This should be removed, if a user needs to provide a username password combination it can be supplied in the `RTSP_IP` parameter as `<username>:<password>@<rtsp_ip>`

**Comment by MS-Nikunja** [comment]
@DavidGrob-V-MS Can you take a look at this.

**Comment by DavidGrob-V-MS** [comment]
@MS-Nikunja sure thing. I'll take a look.

**Comment by v-prsasa** [comment]
@DavidGrob-V-MS Hey David, Is there any update regarding this issue?

**Comment by DavidGrob-V-MS** [comment]
Pull request https://github.com/microsoft/vision-ai-developer-kit/pull/310 from https://github.com/toolboc has been approved and has a fix for the issue
