### ISSUE TITLE
Unable to use the Camera Tagging module

### ISSUE THREAD

**Issue by Teodelas** [microsoft/vision-ai-developer-kit#311]
I built and deployed the Camera tagging module and get the error in the docker logs:
exec user process caused "exec format error"

**Comment by v-prsasa** [comment]
@Teodelas  Just to confirm. Are you referring to this module https://github.com/microsoft/vision-ai-developer-kit/tree/e179b16c6b6f18ff6239407ba5ecf224c838b7e8/samples/official/camera-tagging ?

**Comment by Teodelas** [comment]
Actually this. I had built this for the wrong platform.

**Comment by Teodelas** [comment]
Didn't compile for ARM32
