### ISSUE TITLE
Is Object detection possible using MobilenetSSD with snpe

### ISSUE THREAD

**Issue by PiyalGeorge** [microsoft/vision-ai-developer-kit#312]
Hi, I converted my mobilenetSSD caffe model to .DLC file with snpe APIs. When i run snpe-net-run command it returns .raw files as output. Can i get the detection coordinates to draw the Bounding boxes? Is it possible with this .dlc file?

**Comment by v-prsasa** [comment]
We are looking into it.

**Comment by PiyalGeorge** [comment]
@v-prsasa , Thanks for the reply and effort. This guy has shown me the result - 
https://github.com/globaledgesoft/AIML-Board-App/issues/4#issuecomment-626290832

It will be helpful if you could show me how to run this in qcs605 or similar board. I mean what all snpe files need to copied into the board. I'm copying snpe-1.37.0.788/lib/aarch64-linux-gcc4.9 files, but still getting error.

**Comment by v-prsasa** [comment]
@Devinwong Hi Devin, can you look into this issue?

**Comment by PuneetRahejaMS** [comment]
@PiyalGeorge  the SNPE along with VAIDK firmware is 1.25. If I understand correctly, you are trying to upgrade the firmware to SNPE1.37 in order to run your DLC which was also converted by SNPE 1.37 SDK. This is not trivial and it also needs official support from Qualcomm to make an upgrade.

**Comment by v-prsasa** [comment]
@PiyalGeorge Is this issue resolved?

**Comment by v-prsasa** [comment]
@PiyalGeorge Is your issue resolved?

**Comment by PiyalGeorge** [comment]
Yes @v-prsasa , the issue is resolved. https://github.com/globaledgesoft/AIML-Board-App/issues/4#issuecomment-626290832
Thanks for the help.
