### ISSUE TITLE
[Support Needed] Unable to remotely view camera logs

### ISSUE THREAD

**Issue by smeno004** [microsoft/vision-ai-developer-kit#313]
I have a module deployed on the camera and it has been working as expected. I used to be able to ssh into the camera to check logs. However, recently, I have been trying and failing to view the camera logs by ssh-ing into the device. I checked the ip address on the module twin on azure portal (as well as using adb when directly connected to the device). 

When attempting to ssh, I was unable to connect to that ip address. I have also attempted to connect to http://<ip-address>:3000 on a web browser, and I got a message saying the site could not be reached. Additionally, I tried to view the rtsp stream via VLC media player, and that failed to connect as well. 

I did ensure that my computer was connected to the same wifi as the camera. I am trying to setup a remote connection to the camera to check on its logs (as opposed to physically connect to the device). I wanted to ask here to figure out what I need to check up on to fix this issue. Any help is appreciated.

The current firmware version on the camera is v0.5370. Please advise.

**Comment by v-prsasa** [comment]
@smeno004 Hi Siddhart, Can you reset your device again and try once.
Here is the link to perform the reset-https://azure.github.io/Vision-AI-DevKit-Pages/docs/reset/
You can follow this link.

**Comment by smeno004** [comment]
I have tried to reset the device, but that hasn't fixed the issue.

**Comment by v-prsasa** [comment]
When you configure device, you must wait till it downloads the docker properly it also depends on your network speed. I will suggest you Reset your device by pressing the power button for 12+ seconds and reconfigure it again also delete it from Azure portal.

I will suggest you to try these steps also:
To make sure the RTSP stream for the device is working:

1. Make sure the device is connected to your PC via USB.
2. Open a Command Prompt and Run as Administrator.
3. Enter the command ```cd <platform tools path>```
4. Find the device IP address with the command ```ifconfig wlan0```, and note the IP address after "inet addr:"
5. Use the command ```ping <device IP address>```, ping replies should display.
6. RTSP stream will only work if ping replies display.

**Comment by v-prsasa** [comment]
@smeno004 Is this issue resolved?

**Comment by smeno004** [comment]
@v-prsasa Sorry, I haven't had a chance to test out your suggestions yet. I should be able to do it by tomorrow. I will update when I have done so.

**Comment by smeno004** [comment]
I reset my device and reconfigured it. I found the device IP as you suggested. I pinged it and got replies from within the adb shell. However, when I attempted the ping on my machine through Command Prompt, I received the following reply: "Destination Host unreachable". Is there anything else I can check?

**Comment by v-prsasa** [comment]
@smeno004 When you try to ping from your machine through command prompt you have to change the network it should not be under camera's wifi, It should be in your network.I Tested it in my machine not in adb shell and it is working fine.
I am attaching the screenshot.
<img width="427" alt="VAIDK1" src="https://user-images.githubusercontent.com/58968154/82428246-da3f0300-9aa7-11ea-8b23-2563f926d4e1.PNG">

**Comment by smeno004** [comment]
I ensured that it wasn't under the camera's wifi, but I still get the "Destination host unreachable error" (attaching screenshot). Could this be a firewall issue of some sort that I need to troubleshoot?
![vaidk_troubleshoot_image_1](https://user-images.githubusercontent.com/14913196/82608397-75e77680-9b6f-11ea-96d5-a9aa57578082.jpg)

**Comment by v-prsasa** [comment]
@smeno004  As per my Testing and observation I think so it is some sort of firewall issue from your side because connections and everything is fine. It should work properly.
