### ISSUE TITLE
Missing requirements.txt in sample

### ISSUE THREAD

**Issue by wmeints** [microsoft/vision-ai-developer-kit#314]
Hi, I'm trying to run the sample in https://github.com/microsoft/vision-ai-developer-kit/tree/master/samples/research/VisionSample/MachineLearning/ssd_sample and can't get it to work properly. It seems as if I'm using the wrong version of the required packages. But I can't really figure out how to fix that without a `requirements.txt`. Is there any way that I can find the versions for the different required packages or maybe you can include a `requirements.txt` file in the sample?

**Comment by MS-Nikunja** [comment]
Hi @wmeints, we are looking into it.

**Comment by v-prsasa** [comment]
@DavidGrob-V-MS Can you look into the above issue?

**Comment by v-prsasa** [comment]
@DavidGrob-V-MS Hey david,
Is there any update on this?

**Comment by v-prsasa** [comment]
@drwill-ms Hi David, Can you look into this issue?
Our user is facing issue to run the sample in  https://github.com/microsoft/vision-ai-developer-kit/tree/master/samples/research/VisionSample/MachineLearning/ssd_sample

**Comment by v-prsasa** [comment]
@wmeints Can you update the requirements.txt file with the correct version and run again.
It should work fine

**Comment by v-prsasa** [comment]
@wmeints Is your issue resolved?

**Comment by wmeints** [comment]
Looks like it's working again. Thanks for the support!
