### ISSUE TITLE
http://setupaicamera.ms doesn't resolved

### ISSUE THREAD

**Issue by itsjpavank** [microsoft/vision-ai-developer-kit#316]
I'm able to connect to MSIoT-****** on Wifi. But, still unable to resolve http://setupaicamera.ms

**Comment by v-prsasa** [comment]
@itsjpavank  Hi Pavan,
We will look into this issue.

**Comment by v-prsasa** [comment]
@itsjpavank Can you go through this link-
https://azure.github.io/Vision-AI-DevKit-Pages/docs/quick_start/#configure-the-camera-for-your-wi-fi-network
It has step by step process.

**Comment by itsjpavank** [comment]
@v-prsasa : Yes, I did look at that post. But, that will only work when http://setupaicamera.ms resolves. My problem is, that site doesn't resolve in my local

**Comment by v-prsasa** [comment]
@itsjpavank Are you connected to your camera's wifi while opening this -http://setupaicamera.ms ?

**Comment by itsjpavank** [comment]
@v-prsasa : Yes

**Comment by v-prsasa** [comment]
@itsjpavank At this point after investigating and testing in camera I can say you to do a full factory reset and am sure it will work.Below is the link to reset your device: 
https://azure.github.io/Vision-AI-DevKit-Pages/docs/reset/

**Comment by itsjpavank** [comment]
@v-prsasa : You are talking about following below steps and step 3 wouldn't work again :-)

1. Press power button for 5 seconds setting the device back to Access Point mode
2. When the device is flashing the leds log in to the devices access point
3. Access setupaicamera.ms
4. You’ll be prompted the options to either change WiFi settings or reset the camera.

**Comment by v-prsasa** [comment]
@itsjpavank No sometimes it happens due to some error or connection problem to.. So I just want you to do it again. Can you try once?

**Comment by v-prsasa** [comment]
@itsjpavank What I have observed is when you connect to MSIOT***** it will automatically redirect to http://setupaicamera.ms. No need to open it separately.

**Comment by itsjpavank** [comment]
Unfortunately, it's doesn't redirect

**Comment by v-prsasa** [comment]
@itsjpavank My suggestion would be try to reset once.

**Comment by itsjpavank** [comment]
![image](https://user-images.githubusercontent.com/13517116/83917969-a234f280-a72c-11ea-9f19-1dc632ec241d.png)
![image](https://user-images.githubusercontent.com/13517116/83917978-a6611000-a72c-11ea-99a6-ff31e542aaf3.png)

**Comment by v-prsasa** [comment]
@itsjpavank Is your camera wifi is connected to your wifi properly?
I am giving you the link to troubleshoot wifi problem-https://azure.github.io/Vision-AI-DevKit-Pages/docs/wifi_issues/

**Comment by itsjpavank** [comment]
Since, I'm getting blocked on this path. I have conencted to MSIT_*** via my phone and was able to complete the setup. Finally, landed on to 3000 end point - but I don't see any live stream, is this expected ?

![image](https://user-images.githubusercontent.com/13517116/83920062-d14d6300-a730-11ea-89fa-f71d3c7fdb3d.png)

**Comment by v-prsasa** [comment]
@itsjpavank No, You will see the live stream. It happens due to slow network or slow connection of internet.It takes time to reflect. May be your phone internet connection is slow so it's taking time.

**Comment by itsjpavank** [comment]
It's connected to my home's Wifi (not phone's internet)

**Comment by v-prsasa** [comment]
@itsjpavank Apologies. As I said it must be due to slow connectivity but it will reflect the live webstream. It's not expected to be blank.

**Comment by itsjpavank** [comment]
Yes, indeed - it started to work now.

**Comment by v-prsasa** [comment]
@itsjpavank It's great. Can I close this case the or any other support is required?

**Comment by itsjpavank** [comment]
Yes, please close. I'm good

**Comment by v-prsasa** [comment]
Closing this case as per the confirmation.
