### ISSUE TITLE
Not able to see HDMI/ rtsp output 

### ISSUE THREAD

**Issue by Pratheek-Dev** [microsoft/vision-ai-developer-kit#317]
I have the set up the DevKit following the GetStarted module. I have all four modules (edgeAgent, EdgeHub, AIVisionDevKitGetStartedModule, and WebStreamModule) running on the device. 

**The docker logs for 'WebStreamContainer':**
Listening for incoming mp4 stream on http://127.0.0.1:3001/camera
Awaiting WebSocket connections on ws://127.0.0.1:3002
Webserver listening, configured on port 3000

**Docker logs for `AIVisionDevKitGetStartedModule':**
_Error: Time:Fri Jun 19 15:46:21 2020 File:/usr/sdk/src/c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:1000 Error: io_open failed
Error: Time:Fri Jun 19 15:46:21 2020 File:/usr/sdk/src/c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:2122 failure connecting to address qcs605-32.
send: b'\x89\x80\xab8\x9b\xba'
send: b'\x89\x80-D\xe76'
send: b'\x89\x80\xa5\xed\x08\x98'
send: b"\x89\x80\xdc'\xee\xe8"
send: b'\x89\x807\xc5\xca\x19'
send: b'\x89\x80\xa2\xd5\x88\xaf'
send: b'\x89\x80\xa4/^\xeb'
send: b'\x89\x80S7\xc9\x16'
send: b'\x89\x80]\r\xac\x1d'
send: b'\x89\x80\xf9\xdd\x91\x01'
send: b'\x89\x80\xfa\xc1\xae\x15'
send: b"\x89\x80\xd5\xef\x1c'"_

Earlier I had this error with the VisionAIDevKitGetStarted module:

_gst-launch-1.0  -q  rtspsrc  location=rtsp://<_IP Add_>:8902/live protocols=tcp  !  application/x-rtp, media=application  !  fakesink  dump=true
Error: Time:Thu Jun 18 16:30:58 2020 File:/usr/sdk/src/c/c-utility/adapters/socketio_berkeley.c Func:socketio_dowork Line:1006 Socketio_Failure: Receiving data from endpoint: errno=104.

Confirmation for reported state called with:
    status_code: 204_ 

Is there anything else missing to get the output from the camera?

**Comment by v-prsasa** [comment]
@Pratheek-Dev We will look into this.

**Comment by Pratheek-Dev** [comment]
Hi @v-prsasa what is the recommended stable firmware version to run on the device?

**Comment by v-prsasa** [comment]
@Pratheek-Dev  v0.5370 - Current version 2020-02-26. 
You may find it here - https://store.altek.com.tw/qualcomm/downloads/Azure-IoT-Starter-Kit

**Comment by Pratheek-Dev** [comment]
Would you recommend upgrading to the latest? I get the following from the version output:
adb shell cat /etc/version
v0.2680_Perf

**Comment by v-prsasa** [comment]
Yes you should use latest firmware.Kindly upgrade it and try once again.

**Comment by Pratheek-Dev** [comment]
Thanks, I will update this thread once I do.

**Comment by v-prsasa** [comment]
Yeah sure. Kindly update us after that.

**Comment by Pratheek-Dev** [comment]
Hi @v-prsasa I have the latest firmware, and I am able to see the model scoring, but still can't get the HDMI, webstream, or rtsp to work (get the camera output):

Here is the model log which seems to be working fine:
Found result object
{"confidence": 90, "width": 927.936, "label": "person", "position_x": 24.96, "position_y": 164.916, "id": 2, "height": 895.968}
Confirmation[0] received for message with result = OK
        Properties: {}
        Total calls confirmed: 43
send: b'\x89\x80Y\x8e%\xeb'

**Comment by v-prsasa** [comment]
Can you go through this link-https://azure.github.io/Vision-AI-DevKit-Pages/docs/RTSP_stream/

**Comment by Pratheek-Dev** [comment]
Yes, that's the link I followed already and tested with VLC player

**Comment by v-prsasa** [comment]
Okay.let me try once then

**Comment by v-prsasa** [comment]
Hey, I have tried in my camera and it is working fine. I am attaching screenshot.For me it's working in web stream video. I tried in vlc it's showing some kind of error.I am working on that error. 
Can you try to refresh your web stream page and your camera should be in same network.
![image](https://user-images.githubusercontent.com/58968154/85183282-cbb35980-b2a8-11ea-8516-6605289185d5.png)

**Comment by v-prsasa** [comment]
Hi @Pratheek-Dev , I got to know what's the problem with the rtsp in vlc. While applying the RTSP address in vlc apply the 2nd url which is mentioned. I have attached the screenshot. You can verify from it.
![image](https://user-images.githubusercontent.com/58968154/85183682-2ef1bb80-b2aa-11ea-984f-28690456f42a.png)

![image](https://user-images.githubusercontent.com/58968154/85183636-0c5fa280-b2aa-11ea-8ec1-61d595a7ec77.png)

**Comment by Pratheek-Dev** [comment]
I've tried both of those rtsp URLs neither of them work unfortunately.

**Comment by v-prsasa** [comment]
Can you share me the screenshot that what error you are getting?

**Comment by v-prsasa** [comment]
@Pratheek-Dev Hey pratheek, Is your issue resolved ? if not can you attach the screenshot of the error which you are getting?

**Comment by Pratheek-Dev** [comment]
Hi @v-prsasa I tried resetting the device and recreating a new IoT Edge Device, but the same issue persists: 

This site can’t be reached 192.xxx.x.xx refused to connect.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED

Can you share which images are running on your device? Are they the stock images found on the IoT Kit? I will try to rebuild the deployment manifest with the images you are using

**Comment by v-prsasa** [comment]
@Pratheek-Dev Hey Pratheek, 
First of all I want to say if it's connection problem then Open your WiFi settings and disconnect your workstation from the camera (MSIoT_B9D4B6). Note that your workstation and this camera should be on the same Wi-Fi network in order to view the web stream. You should be able to see the camera video output within minutes. Make sure it is plugged in to an HDMI monitor .
I am attaching a screenshot what are the things running in my device-
<img width="950" alt="P2" src="https://user-images.githubusercontent.com/58968154/85629733-08f45e80-b690-11ea-9813-dd614cecf41d.PNG">

**Comment by Pratheek-Dev** [comment]
Thanks for your help @v-prsasa . I have the webstream working now, but the HDMI is still having issues, I'll try with another cable just in case.

**Comment by v-prsasa** [comment]
@Pratheek-Dev Great, Thanks for the update Pratheek . So can we close this case now or do you need further support?

**Comment by v-prsasa** [comment]
@Pratheek-Dev Can we close this case now? or you need further support?

**Comment by Pratheek-Dev** [comment]
@v-prsasa I'm attempting to find another HDMI monitor/cable to test with, since the output isn't shown via HDMI.

**Comment by v-prsasa** [comment]
Ok no issues, Once you are done kindly update us.

**Comment by v-prsasa** [comment]
@Pratheek-Dev Hey Pratheek, Is your issue resolved with HDMI cable?

**Comment by Pratheek-Dev** [comment]
Hi @v-prsasa I tested with a new monitor and it works now! looks like it doesn't work on some monitors.
