### ISSUE TITLE
Can I upgrade the version of Python on the device to 3.8.3?

### ISSUE THREAD

**Issue by lokijota** [microsoft/vision-ai-developer-kit#318]
Or will this break something?

**Comment by v-prsasa** [comment]
@lokijota We are looking into this issue and will get back to you.

**Comment by v-prsasa** [comment]
@lokijota Hey,
As per my investigation there is no upgraded version of python. You can follow the below link :
https://azure.github.io/Vision-AI-DevKit-Pages/docs/SetUp_VS_Code/#setup-and-configure-vs-code-for-container-deployment

Even for windows the latest on is python 3.7
![image](https://user-images.githubusercontent.com/58968154/85632212-891cc300-b694-11ea-94ca-8dd042c63e73.png)

**Comment by lokijota** [comment]
Hi. What I mean is this: the device is running 3.5.3. Can I update to 3.8.3, the latest version? Will it break the SDK?

Link to 3.8.3 here: https://www.python.org/downloads/release/python-383/

**Comment by v-prsasa** [comment]
@lokijota Hi Joao, AS I have tested and it is working fine So you can go forward and update to 3.8.3, It won't break the SDK.

**Comment by v-prsasa** [comment]
@lokijota Can we close this issue if no further support is required?

**Comment by lokijota** [comment]
Yes, go ahead. Thanks.

**Comment by v-prsasa** [comment]
Closing as per the user confirmation.
