### ISSUE TITLE
Readme.md file cannot be found

### ISSUE THREAD

**Issue by itsjpavank** [microsoft/vision-ai-developer-kit#320]
Refer to modules/AIVisionDevKitFaceAPIModule/python_iotcc_sdk/README.md to develop and test source code for a new AIVisionDevKitFaceAPIModule.

**Comment by v-prsasa** [comment]
@itsjpavank Hi Pavan, We will look into it.

**Comment by v-prsasa** [comment]
@itsjpavank You can find the README.md file here in camera sdk-
https://github.com/microsoft/vision-ai-developer-kit/blob/master/camera-sdk/README.md

**Comment by v-ragala** [comment]
@itsjpavank Hi Pavan, is there any update on this. is your issue resolved?

**Comment by v-prsasa** [comment]
@itsjpavank Hi Pavan, Any update on the above issue ?

**Comment by itsjpavank** [comment]
I'm good, please close the ticket.

Thanks,
Pavan
Sent from Phone

________________________________

**Comment by MS-Nikunja** [comment]
@itsjpavank, thanks for the confirmation.
