### ISSUE TITLE
Transfer learning sample notebook fails to score

### ISSUE THREAD

**Issue by Pratheek-Dev** [microsoft/vision-ai-developer-kit#321]
Hi,

I've created and deployed a custom transfer learning model using the exact same code from the sample notebook here: https://github.com/microsoft/vision-ai-developer-kit/blob/master/machine-learning-notebooks/02-mobilenet-transfer-learning.ipynb 

I am not able to retrieve any scores from the soda_cans sample model using the provided data in this GitHub. I have also tested with my own data set for another model, but the issue remains the same (here is the output from the sodacans module - it's stuck on 'pepsi' as the label, so the last label in "output_labels.txt" file is what is displayed no matter what soda can I test with the camera, it is the same with other object detection models I've trained with using mobilenet).

Can we confirm the sample notebook is up to date, please?:

Confirmation[0] received for message with result = OK
    Properties: {}
    Total calls confirmed: 3664
id=1
label=pepsi
confidence=91
Position(x,y,w,h)=(0.0,0.0,0.0,0.0)

Confirmation[0] received for message with result = OK
    Properties: {}
    Total calls confirmed: 3665
id=1
label=pepsi
confidence=91
Position(x,y,w,h)=(0.0,0.0,0.0,0.0)

Confirmation[0] received for message with result = OK
    Properties: {}
    Total calls confirmed: 3666
id=1
label=pepsi
confidence=91
Position(x,y,w,h)=(0.0,0.0,0.0,0.0)

Confirmation[0] received for message with result = OK
    Properties: {}
    Total calls confirmed: 3667

**Comment by MS-Nikunja** [comment]
Hi @Pratheek-Dev, we will get back to you on this.

**Comment by v-prsasa** [comment]
@Pratheek-Dev Hi Pratheek, We are checking with the team internally whether the sample notebook is up to date or not. We will get back to you soon.

**Comment by Pratheek-Dev** [comment]
Adding more information: 

I've tried rebuilding the AIVisionGetStartedModule image with the retrained Soda_Cans model (trained in Azure ML Workspace). however, the same error results as mentioned in the issue:

Found result object
{"height": 0.0, "position_y": 0.0, "confidence": 91, "id": 3, "position_x": 0.0, "label": "pepsi", "width": 0.0}
Confirmation[0] received for message with result = OK
        Properties: {}
        Total calls confirmed: 19
send: b'\x89\x80LDN\x1f'
Found result object
{"height": 0.0, "position_y": 0.0, "confidence": 91, "id": 3, "position_x": 0.0, "label": "pepsi", "width": 0.0}
Confirmation[0] received for message with result = OK
        Properties: {}
        Total calls confirmed: 20
send: b'\x89\x80%D\xa4x'
Found result object
{"height": 0.0, "position_y": 0.0, "confidence": 91, "id": 3, "position_x": 0.0, "label": "pepsi", "width": 0.0}
Confirmation[0] received for message with result = OK
        Properties: {}
        Total calls confirmed: 21
send: b'\x89\x80\xa8\x97\xa1\n'
send: b'\x89\x80\xac6\x87\xa8'
Found result object
{"height": 0.0, "position_y": 0.0, "confidence": 91, "id": 3, "position_x": 0.0, "label": "pepsi", "width": 0.0}
Confirmation[0] received for message with result = OK

**Comment by Pratheek-Dev** [comment]
@MS-Nikunja @v-prsasa Would it be easier if I shared my model.dlc file + va-snpe-engine-library_config.json that were created and registered in Azure ML Workspace? could the issue be with the snpe converter  that is being used in the notebook?

**Comment by v-prsasa** [comment]
@Pratheek-Dev Thanks for the information. We will look into this?

**Comment by v-prsasa** [comment]
@DavidGrob-V-MS Can you help Pratheek with this issue. As sample notebook is updated so it's not an issue with the sample notebook.

**Comment by Pratheek-Dev** [comment]
@Hi @v-prsasa any update on this?

**Comment by v-prsasa** [comment]
@Pratheek-Dev Sorry for the Delay. We have added David in this thread because he can give clear idea about the sample notebook and the error you are getting. We will check with David on this.

**Comment by Pratheek-Dev** [comment]
thanks @v-prsasa, please let me know if there is any additional information needed.

**Comment by v-prsasa** [comment]
@Pratheek-Dev Yeah sure.

**Comment by lokijota** [comment]
Just to add a +1 here. I've never been able to get custom models running on the kit. Either the sample or models converted with snpe/qualcoom's tools.

**Comment by v-prsasa** [comment]
@Devinwong Hey Devin, Can you look into this issue?

**Comment by Pratheek-Dev** [comment]
@v-prsasa @MS-Nikunja Any update on this?

**Comment by MS-Nikunja** [comment]
@Pratheek-Dev, we are extremely sorry for the delay. We will check with Devin on this and let you know.

**Comment by Pratheek-Dev** [comment]
hi @MS-Nikunja @v-prsasa  any idea what  the issue might be? still having trouble getting custom models working, other individuals have also had the same issue

**Comment by Pratheek-Dev** [comment]
Hi @MS-Nikunja @v-prsasa @Devinwong the customvision.ai models trained over the past few days are also not scoring..

**Comment by MS-Nikunja** [comment]
Hi @Pratheek-Dev We are discussing it internally and that's why it is taking some time. We will update you ASAP. Thanks for the update and thank you so much for your patience.

**Comment by v-prsasa** [comment]
@Pratheek-Dev Hi Pratheek,
We have an update from Devin, Please look into it.
I just try deploying a model from custom vision and it works.

Below are the screen shots.

  Loading image...   Loading image...  

 

Regarding the AML notebooks, I was not the one who delivered that part. Not sure if Mike McCoy knows.

Afaik, the transfer learning notebooks retrains the model based on tensorflow and then convert to Qualcomm’s dlc.

The conversion at the backend calls Qualcomm SNPE SDK.

I guess there is a mismatch between the converter version at AML backend (which is too old) and the vision ai dev kit firmware. Both were frozen about a year ago.

I don’t remember the versions though.

Hope this helps.

**Comment by lokijota** [comment]
Hi @v-prsasa ,

is there any way to get a custom ML model running on the camera, or plans to fix the situation you're talking about? 

being limited to CustomVision.ai's models is a huge limitation, however well this works. A few months ago I trained a few models, converted with Qualcomm's tooling (which was a world of pain to set up), only to have it simply not work with no logs helping to diagnose the situation. The provided samples, as @Pratheek-Dev highlighted, also don't work.

It'd be good to know **when** will this be fixed. If it's not going to be fixed, the respective samples have to removed ASAP and anything aluding to the capability be ammended - and btw call it it "CustomVision.ai DevKit", not the Vision AIDK.

Thanks.

**Comment by v-prsasa** [comment]
@Devinwong Hi Devin , Can you please look into the above issue?

**Comment by v-prsasa** [comment]
@Devinwong Could you please give us update on this?
@Pratheek-Dev Are you clear with Devin's reply?

**Comment by v-prsasa** [comment]
@Pratheek-Dev Any update on this issue?

**Comment by v-prsasa** [comment]
@Pratheek-Dev We are closing this case as there is no response from your end, kindly reopen this issue if required.
