### ISSUE TITLE
Connection String ID for Altek AI Camera IoT Device

### ISSUE THREAD

**Issue by agryguc** [microsoft/vision-ai-developer-kit#323]
Just curious what the syntax for the connection string ID to add the IoT device to a IoT hub in Azure during the setup process. The camera keeps trying to connect, but it hangs on this screen and eventually fails...

![Connection_String_Error](https://user-images.githubusercontent.com/60630377/89305458-a9994f00-d63c-11ea-8b7d-ee92e0e2dd52.JPG)

This is what the general syntax of the connection string looks like:

![pastedImage](https://user-images.githubusercontent.com/60630377/89305477-af8f3000-d63c-11ea-9d39-f4710d6831ae.png)

**Comment by v-prsasa** [comment]
@agryguc Hi, We will look into it and get back to you asap.

**Comment by v-prsasa** [comment]
@agryguc According to our testing if the camera keeps trying to connect, but it hangs on this screen and eventually fails means there is a problem with connectivity. If the network connection is slow it takes time to connect and then it fails.
If you have IoT edge connection string then give it otherwise you can go n click the next button.
Here is the link for reference- https://azure.github.io/Vision-AI-DevKit-Pages/docs/quick_start/#configure-your-camera-to-connect-to-azure-as-an-iot-edge-device.

**Comment by agryguc** [comment]
@v-prsasa - thanks for your response. I dont believe there is an issue with connectivity.... I was referencing the quick-start guide throughout the process of getting it configured. What I am asking is the about the syntax for the connection string to connect the camera to Microsoft Azure? T I don't believe I am using the correct device ID or, host name or shared access key,  what are those? It still hangs on the screen and eventually fails irrelevant of what device ID/hostname/access key I put, so I am not sure I am using the correct syntax. Please advise.

**Comment by v-prsasa** [comment]
@agryguc Yeah I understand your problem . Are you trying to configure it for first time or you have done before? If it's first time then you don't need any device ID/hostname /access key. You should click on next button and continue with further process.
Because according to our testing it's working fine.

**Comment by agryguc** [comment]
@v-prsasa thanks, but intuitively that is what I initially tried (no connection string just clicking next), but it does need one to proceed as it states "invalid connection string" when you leave it blank...

![Capture](https://user-images.githubusercontent.com/60630377/89550675-ec435e80-d7d7-11ea-9cd8-6296c393b6ac.JPG)

**Comment by v-prsasa** [comment]
@agryguc I am attaching my screenshots step by step for your reference. Kindly go through it.
![Picture1](https://user-images.githubusercontent.com/58968154/89572661-0f592700-d847-11ea-94f4-53c127a9acc2.png)
![Picture2](https://user-images.githubusercontent.com/58968154/89572705-20099d00-d847-11ea-868f-d8e7f19ebc10.png)
<img width="468" alt="Picture3" src="https://user-images.githubusercontent.com/58968154/89572718-2435ba80-d847-11ea-99af-f6d4c5a8da24.png">
![Picture4](https://user-images.githubusercontent.com/58968154/89572721-24ce5100-d847-11ea-9998-a11b8715880a.png)
![Picture6](https://user-images.githubusercontent.com/58968154/89572723-26981480-d847-11ea-9484-2f80a4e146af.png)
![Picture7](https://user-images.githubusercontent.com/58968154/89572730-27c94180-d847-11ea-8623-970570256b3d.png)
![Picture12](https://user-images.githubusercontent.com/58968154/89572765-36aff400-d847-11ea-8a2a-2248c7a7751b.png)
![Picture13](https://user-images.githubusercontent.com/58968154/89572771-3a437b00-d847-11ea-9997-4a40d17f55c7.png)
![Picture14](https://user-images.githubusercontent.com/58968154/89572785-3f082f00-d847-11ea-8bf1-ed6fa6d7f693.png)
![Picture8](https://user-images.githubusercontent.com/58968154/89572861-5b0bd080-d847-11ea-859b-f5e09196ef01.png)
![Picture9](https://user-images.githubusercontent.com/58968154/89572868-5cd59400-d847-11ea-821b-0003146bbe61.png)
![Picture10](https://user-images.githubusercontent.com/58968154/89572871-5e06c100-d847-11ea-9e43-471d9986dba1.png)
![Picture11](https://user-images.githubusercontent.com/58968154/89572874-5f37ee00-d847-11ea-88f9-9644f1c9c2f1.png)

**Comment by agryguc** [comment]
Thanks, but I followed the setup walkthrough already, your device uses a device code to connect, this one does not.... it requries a connection ID string... I need to simply know what the synatax I should be using for this string? There are no other options like the one you suggest below:

![image](https://user-images.githubusercontent.com/60630377/89573620-dd20d880-d7f8-11ea-9e71-3a3fcfc2b66e.png)

The only option is with an IoT Edge connection string like below:

![image](https://user-images.githubusercontent.com/60630377/89573658-ee69e500-d7f8-11ea-9500-dd6ea68e992f.png)


Please advise.

**Comment by v-prsasa** [comment]
@agryguc I got your point, So according to my observation and testing the syntax i.e for hostname,shared accesskey and device id 
HostName=Priyanka-Hub.azure-devices.net; SharedAccessKeyName=device; SharedAccessKey=xBdz+R5jDk7sbir4wx3FZL8H2fUOu8+AzcYTOuGCfJg=

**Comment by agryguc** [comment]
@v-prsasa  thanks, where did the access key info come from? And the host name? And the shared access key name? Can you give me an idea if any of those are the SSID/password or S/N of the actual device or are they the SSH remote login credentials????

**Comment by v-prsasa** [comment]
@agryguc Yeah sure, It relate to the IoT hub information that you setup in Azure.  There is Settings in that portal. In settings you have to go to Shared access policies and then you can go to device. If you click on device you can see the shared access keys. I am attaching a screenshot for your reference too.
<img width="957" alt="A1" src="https://user-images.githubusercontent.com/58968154/89583490-0e7cc100-d858-11ea-97ba-208e8ba50523.PNG">

**Comment by agryguc** [comment]
@v-prsasa thanks that makes alot more sense. I am trying to reset the camera because the SSID network isnt showing up on my computer anymore (my guess is it partially got through the configuration process and isnt allowing me to connect to it to restart the setup process again at http://setupaicamera.ms/)

I held the small reset button on the back of the device for over 30 seconds until an audible "click noise" was heard, then I plugged everything back in and the camera's network still doesnt show up on any of my computers.... any advice here? Because of that when I try and access the camera now for setup it wont allow me to connect...

![image](https://user-images.githubusercontent.com/60630377/89673486-72cd6e00-d8b4-11ea-89f9-08bb657029fb.png)


Thanks,
Andrew

**Comment by v-prsasa** [comment]
@agryguc Actually it should work after all this reset. Can you try to do full factory reset.
Here is the link for your reference- https://azure.github.io/Vision-AI-DevKit-Pages/docs/reset/

**Comment by agryguc** [comment]
Still 3 flashing red lights (setup mode) and no wifi network showing up. The first step of the reset process you sent via the link is  to press the "power button" for 5 seconds... this device has no power button, only a small pinhole reset button. Please advise.....

**Comment by v-prsasa** [comment]
@agryguc Yeah you are correct that there is a small pinhole reset button, just press the "power button" for 5 seconds and restart it. Try to reset and configure everything from starting.

**Comment by agryguc** [comment]
@v-prsasa  - so there is no power button on this device at all, as in it doesnt exist.... There only is the small pinhole reset button which I have tried multiple times and reset/rebooted the device, but still the SSID device wifi-network does not show up on my wifi tray and the device then continues to flash three red lights.

**Comment by v-prsasa** [comment]
@agryguc  Yeah I understood your problem of SSID device wifi-network does not show up on your wifi tray. I need you to do full reset means reboot your device from scratch means- Go to this folder->PEABODY_QCS603_LE_r37-v0.5370_Perf->v0.5370_Perf and run FastbootUpgrade_v6_5 this one.and then it will work most probably. Just try it out till then I will try in my device.

**Comment by agryguc** [comment]
@v-prsasa, with the camera plugged in via USB running that batch-file fails...

![image](https://user-images.githubusercontent.com/60630377/89796368-96342b00-daf7-11ea-9dbc-3ec654b8bb9a.png)

Please let me know if there is anything else I can try.

**Comment by v-prsasa** [comment]
@agryguc If the batch-file fails means the device is not plugged in via USB properly. Please just try to check whether it is connected properly via adb tool.

**Comment by agryguc** [comment]
@v-prsasa - thanks, can you explain where the adb tool is located?

**Comment by v-prsasa** [comment]
@agryguc Yeah sure, When you connect your device via USB cable then open command prompt and type the following command-
>adb
>adb devices
I am attaching screenshot for your reference-
<img width="599" alt="Image1" src="https://user-images.githubusercontent.com/58968154/89809286-f909de80-db58-11ea-8cc3-e8a01e3c4b67.PNG">

**Comment by agryguc** [comment]
@v-prsasa  - no luck unfortunately

![image](https://user-images.githubusercontent.com/60630377/89809918-427f0d00-db0a-11ea-9d6c-17ea3b81f401.png)

**Comment by v-prsasa** [comment]
@agryguc yes it won't work, because you have to install platform tools for this.
Kindly refer to this document- https://azure.github.io/Vision-AI-DevKit-Pages/docs/platform_tools/

**Comment by agryguc** [comment]
Still no luck......

![image](https://user-images.githubusercontent.com/60630377/89816534-bde5bc00-db14-11ea-8670-c852e0387d69.png)

**Comment by v-prsasa** [comment]
@agryguc Okay let me explain you with full process-
1)Download Platform-tools_r30.0.4
2)Add the platform tools path in your environment variables path i.e Go to System properties -> Advanced -> Environment variables -> Go to Path -> Add the platform tools path there -> and then click on OK
I think after this it will work.

**Comment by agryguc** [comment]
@v-prsasa - still no luck.... adding the platform tools bath to the user and system variables still doesnt make a difference when I run adb devices

![image](https://user-images.githubusercontent.com/60630377/89821570-c9d57c00-db1c-11ea-9343-83996bfa6492.png)

Command prompt pops up briefly when I run adb.exe, but nothing else noticeable happens....

![image](https://user-images.githubusercontent.com/60630377/89821663-f5f0fd00-db1c-11ea-8da3-2f767c7dc64f.png)

Still no luck running adb devices...

![image](https://user-images.githubusercontent.com/60630377/89821693-01442880-db1d-11ea-8d2c-009c3d44c796.png)


There has got to be an easier way to do this... can we not troubleshoot connectivity in device manager? The camera was working before, once I tried the actual syntax of the connection string it froze and I was unable to get it to reboot/reset so that I could try re-configuring it from scratch....

**Comment by v-prsasa** [comment]
@agryguc Can you tell me which firmware version you are using?

**Comment by agryguc** [comment]
@v-prsasa I have never updated the firmware from what it shipped with. I dont even know how to check to be honest...

**Comment by v-prsasa** [comment]
@agryguc Can you download the latest firmware from the below link-
https://azure.github.io/Vision-AI-DevKit-Pages/docs/Firmware/

**Comment by agryguc** [comment]
Step 2 of the link you just sent literally contains the issue we are having with adb tools, so I haven't been able to update the firmware...... (I tried this over a week ago with no luck)... Please advise how I should proceed

![image](https://user-images.githubusercontent.com/60630377/89825185-330bbe00-db22-11ea-85ab-f7a7f141f419.png)

**Comment by v-prsasa** [comment]
@agryguc Once you update the firmware to latest version it will start working. Let me check from my end once until then can you try again.

**Comment by agryguc** [comment]
Understood, I have been trying to update the firmware for the past week, but I will try again. Please let me know if you figure out a workaround.

**Comment by agryguc** [comment]
@v-prsasa - any word on how to fix this problem, still no luck updating the firmware.

**Comment by v-prsasa** [comment]
@agryguc As per my testing in the device it is working once firmware is updated.

**Comment by agryguc** [comment]
@v-prsasa - any suggestions on how I can get update the firmware without ADB tools or use some other workaround?

**Comment by v-prsasa** [comment]
@agryguc This is the only way to update firmware with adb tools which is given in the links- https://azure.github.io/Vision-AI-DevKit-Pages/docs/Firmware/#download-and-extract-the-latest-firmware

**Comment by agryguc** [comment]
@v-prsasa - so what do you recommend I do then? Since ADB devices is continually not recognized and "device is not attached"? Giving me the same information that I have had for the past two weeks and was literally the first thing I tried following the issue isn't a terribly useful workaround.

**Comment by v-prsasa** [comment]
@agryguc Can you please share screenshots of the steps you are following ? It will be helpful for me

**Comment by v-prsasa** [comment]
@agryguc I would like to suggest you when you download the platform tools, extract the zip files and set the path of the extracted zip file (platform tools) in command prompt. I have attached the screenshot, kindly look into it.
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/58968154/90068592-88a4be00-dd0e-11ea-8d75-7b510a79d16f.png)
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/58968154/90068640-9ce8bb00-dd0e-11ea-9b80-499e8ca9f870.png)

**Comment by agryguc** [comment]
Okay, that worked, now do I try updating the firmware?

![image](https://user-images.githubusercontent.com/60630377/90071714-0c858880-dcc4-11ea-9bcb-c4237a69ddce.png)

**Comment by v-prsasa** [comment]
@agryguc No need to update now, you

**Comment by v-prsasa** [comment]
@agryguc No need to update now, you can start the further process

**Comment by agryguc** [comment]
@v-prsasa - after copying the windows specific batch files to the firmware directory and doubleclicking the "FastbootUpgrade_v6_5.bat" file... it still says device is not attached, despite it being recognized in the list of devices using adb devices in a separate command prompt

![image](https://user-images.githubusercontent.com/60630377/90073231-d85f9700-dcc6-11ea-83a7-bbd8bd228b0d.png)

**Comment by v-prsasa** [comment]
@agryguc Which firmware version you are using? The latest one is v0.5370 and if you are using latest version then no need to perform this step. You can skip this and reboot this by using this command - adb shell cat /etc/version.

**Comment by agryguc** [comment]
I dont know what firmware is on the device, how do I check that? The firmware I had downloaded was v0.5370. I will try rebooting, but using that command did not yield anything.... I am assuming I need to replace "version" with the version number?

![image](https://user-images.githubusercontent.com/60630377/90074788-ed89f500-dcc9-11ea-83e1-60505d3bb3ff.png)

**Comment by v-prsasa** [comment]
@agryguc No need to replace version with version number. By using this command -adb shell cat /etc/version youcan check the firmware version. First try to reboot the device by using adb reboot command.

**Comment by agryguc** [comment]
Device audibly clicked using the adb reboot command (and the flashing red lights went solid red for about 10 seconds), then returned to flashing red (setup mode).  The devices has v.0.2680 version of the firmware.

![image](https://user-images.githubusercontent.com/60630377/90079481-0e584780-dcd6-11ea-9a26-beed1281dc4e.png)

**Comment by v-prsasa** [comment]
@agryguc It's the older version firmware. Please update it to latest version. You can refer to the link-https://azure.github.io/Vision-AI-DevKit-Pages/docs/Firmware/#update-the-firmware

**Comment by agryguc** [comment]
@v-prsasa - yes, I did that (and have been trying to update the firmware for the past two weeks). When I run the batch file nothing happens.... after copying the windows specific batch files to the firmware directory and doubleclicking the "FastbootUpgrade_v6_5.bat" file... it still says device is not attached

![image](https://user-images.githubusercontent.com/60630377/90079858-0e0c7c00-dcd7-11ea-8105-55b7db3e1f6c.png)

**Comment by v-prsasa** [comment]
@agryguc Let me clear things here when you are connecting your device and running the ADB command that time ADB is showing list of the devices, once it shows the list of devices then you run the "FastbootUpgrade_v6_5.bat" file. This is the process.

**Comment by agryguc** [comment]
Okay, do run it from the same cmd window? or do I double click on the batch file in the firmware directory? How do I run it from the cmd window? None of that information is stated in the firmware update link....

https://azure.github.io/Vision-AI-DevKit-Pages/docs/Firmware/#update-the-firmware

**Comment by v-prsasa** [comment]
@agryguc No dont't run it from same cmd window. Double click on the batch file in the firmware directory.

**Comment by agryguc** [comment]
Okay, that hasnt worked the last 20-30 times I have tried it over the past 2 weeks.... so I doubt it will work now.... and to confirm trying that again. Still says device is not attached. 

![image](https://user-images.githubusercontent.com/60630377/90081754-3054c880-dcdc-11ea-8c27-44651527e277.png)

**Comment by v-prsasa** [comment]
@agryguc Did you try to reset it again ?

**Comment by agryguc** [comment]
Yes, tried rebooting twice again and same thing when clicking the batchfile to update the firmware. Also, the device SSID is still not showing up in the wifi tray.

![image](https://user-images.githubusercontent.com/60630377/90171511-9dfe0480-dd6f-11ea-91d0-9635a369c9d4.png)

**Comment by v-prsasa** [comment]
@agryguc According to my testing it's working, Can you check device battery level ? by using this command- adb shell cat /sys/class/power_supply/battery/capacity , Because when the battery is less than 50% this batch file won't run.

**Comment by agryguc** [comment]
Battery level is 100% 

![image](https://user-images.githubusercontent.com/60630377/90175855-149e0080-dd76-11ea-924e-9272dfe141e8.png)

**Comment by v-prsasa** [comment]
@agryguc Then it should work !

**Comment by agryguc** [comment]
@v-prsasa - well it does not.... this was literally the issue since day one... please advise how I should proceed. For some reason the firmware isnt flashing....... all of this other diagnostic information just confirms the issue I originally had as I followed the instructions verbatim. Please advise. Running the batch file to flash the firmware as an administrator still does the following. 

![image](https://user-images.githubusercontent.com/60630377/90187537-efb28900-dd87-11ea-8a8a-5062f0f5682a.png)

**Comment by agryguc** [comment]
@v-prsasa - any ideas on why the batch file to upgrade the firmware isnt running properly?

**Comment by v-prsasa** [comment]
@agryguc moslt it doesn't work when the battery power is less than 50% .

**Comment by agryguc** [comment]
@v-prsasa - yes, I have ensure the battery level is 100% multiple times while trying to flash the firmware, yet it still doesn't work. Please advise as to next steps and/or workarounds....

**Comment by v-prsasa** [comment]
@agryguc I have provided you all the steps and workaround still you are facing the problem. Let me check with my team internally.

**Comment by agryguc** [comment]
@v-prsasa - thank you, much appreciated. I look forward to your response.

**Comment by agryguc** [comment]
@v-prsasa - any updates with your discussions from your team internally?

**Comment by v-prsasa** [comment]
@agryguc Yes, Everyone is able to connect it to adb and fastboot upgrade works for them. Still wondering why the issue occurs with you. Have you tried again?

**Comment by v-prsasa** [comment]
@agryguc Any update on this issue?

**Comment by agryguc** [comment]
Unfortunately not, still having the same issues as previous. Unable to flash new firmware.

-Andrew
________________________________

**Comment by v-prsasa** [comment]
@agryguc Closing this issue as it was camera hardware problem. provided new camera hope it works.
Kindly open new issue if required.
