### ISSUE TITLE
Accessing WebStream module after deploying trained model

### ISSUE THREAD

**Issue by MadanKrishnan97** [microsoft/vision-ai-developer-kit#324]
I have a trained model that I deploy to the Vision AI camera (Reference - [link](https://github.com/microsoft/vision-ai-developer-kit/blob/master/machine-learning-notebooks/04-Deploy-Trained-Model.ipynb)). Once I am done with this, I need to view the output of the model and the camera field using the WebStream module (Reference - [link](https://github.com/microsoft/vision-ai-developer-kit/blob/master/machine-learning-notebooks/04-Deploy-Trained-Model.ipynb)). Once I add the WebStream module to the kit, I am able to access http://device_ip:3000, but I cannot view the stream. Am I doing something wrong?

**Comment by MS-Nikunja** [comment]
Hi @MadanKrishnan97, we will get back to you on this.

**Comment by v-ragala** [comment]
Hi @MadanKrishnan97,  Can you please refer bellow mention link for your connectivity issue. https://azure.github.io/Vision-AI-DevKit-Pages/docs/Tutorial-HOL_Using_the_VisionSample/

**Comment by v-ragala** [comment]
Hi, Can you please refer below mention link for your issue. https://azure.github.io/Vision-AI-DevKit-Pages/docs/Deploy_Model_IoT_Hub/

**Comment by MadanKrishnan97** [comment]
> Hi, Can you please refer below mention link for your issue. https://azure.github.io/Vision-AI-DevKit-Pages/docs/Deploy_Model_IoT_Hub/

**Comment by MadanKrishnan97** [comment]
Hello. Does it mean that I should not be doing the deployment step in this link https://github.com/microsoft/vision-ai-developer-kit/blob/master/machine-learning-notebooks/04-Deploy-Trained-Model.ipynb? Instead I should the generated URI and follow the deployment steps in the Azure wizard as suggested? Thanks!

PS: Sorry about closing the issue, it was a mistake.

**Comment by v-ragala** [comment]
Dear @MadanKrishnan97 Yes, both the doc is same its deep doc which I have shared you.

**Comment by v-prsasa** [comment]
@MadanKrishnan97 Hi , Is this issue resolved ?

**Comment by MadanKrishnan97** [comment]
Hi @v-ragala @v-prsasa. I haven't had the opportunity to try out the suggested method. I will try it out soon and provide an update. Thank you for your patience.

**Comment by v-prsasa** [comment]
@MadanKrishnan97 Thanks for the update. We will wait for your response.

**Comment by v-prsasa** [comment]
@MadanKrishnan97 Any updates on this issue? Is it resolved?

**Comment by MadanKrishnan97** [comment]
Hi @v-prsasa. I am having issues with deploying custom models. Though the dlc conversion happens successfully, the deployment is not successful in the device. This is a different issue, and will create a new one for the same. But regarding the WebStream module, I could not get the video access and cannot confirm what the reason is. I got a workaround by using RTSP.

**Comment by MS-Nikunja** [comment]
@MadanKrishnan97, Great! So we will go ahead and close this issue.

**Comment by MadanKrishnan97** [comment]
@MS-Nikunja Thank you. Yes, please do!
