### ISSUE TITLE
Firmware upgrade fails from 3530 to 5370

### ISSUE THREAD

**Issue by raaznaren** [microsoft/vision-ai-developer-kit#331]
Hello,

I´m trying to update the firmware of the devkit to 0.5370_perf. I can see my device connected via adb devices but when I click in FastbootUpgrade_v6_5.bat like the instructions said the device become disconnected (red lights) and it fails. I also follow the instructions from [here](https://azure.github.io/Vision-AI-DevKit-Pages/docs/Recover_device/#recover-vision-ai-dev-kit-hardware-after-a-failed-firmware-update) to solve but it fails too at adb reboot bootloader step with same exception.

This is the error I get when I execute FastbootUpgrade_v6_5.bat

"Check adb device..."
"Device is not attached(X)"
"Fastboot upgrade fail(X)"
Press any key to continue . . .

Docker PS also not connecting after first attempt of update, details below of docker ps command.
DevKitFirmware>adb shell
/ # docker ps
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
/ #

Few things tried:
1. Charged battery to 90+ and tried with no luck
2. Hard reboot by pressing for 12sec(from [this](https://github.com/microsoft/vision-ai-developer-kit/issues/279) recommendation). Device is identified by adb devices but fails with same exception when try to update.
3. Tried recovery but it also fails with same exception.

As suggested [here](https://github.com/microsoft/vision-ai-developer-kit/issues/279) , I tried all solutions recommended except trying from MAC OS(I do not have MAC OS but tried from 3 different windows 10 devices with no luck).

Can you please help?  Thanks!

**Comment by raaznaren** [comment]
Update: I tried with my PI 4 linux and it worked after lot of issues. Major issues found are listed below and request to correct the linux version .sh scripts.

1. Upgrade bash is not installing when the device battery is 100%. Screenshot for reference ![reference](https://user-images.githubusercontent.com/16771132/102711166-85957d80-426c-11eb-9b6e-eea7e5f61701.png)
2. Script is not checking if the device/OS has adb and fastboot installed. It would be good if we can generate some warning message with steps to install both adb and fastboot which are required for this installation.
3. We may need to increase the initialize time as 100 * 4 is not helpful. Few times it took more time and verification bash failed.

Also, would be interested on what was the issue with windows version of script. Thanks!

**Comment by v-prsasa** [comment]
@raaznaren Please allow us some time, we are looking into this issue.

**Comment by v-prsasa** [comment]
@raaznaren Hi, I would suggest instead of upgrading it in this way i.e. try to install the firmware from here-https://store.altek.com.tw/qualcomm/downloads/Azure-IoT-Starter-Kit and run it. 
For me it is working fine. Try to do a factory reset if possible.

**Comment by raaznaren** [comment]
@v-prsasa - As I mentioned, I already resolved using linux variant OS. My overall experience was too bad with AI Dev kit as I'd spent almost 4-5 hours to set it up and running and now having issues with pushing models. 

I may not waste anymore time on this. Please go ahead and close this issue. Thanks!
