### ISSUE TITLE
Can't connect a new device to iot edge via connection string. Also unable to update firmware.

### ISSUE THREAD

**Issue by mrzutshi** [microsoft/vision-ai-developer-kit#333]
I am setting up the Vision AI kit for the first time, which is currently using the firmware version v0.2600_Perf. I am facing a separate problem in updating the firmware to the latest version.
 
While configuring the device, I reach the step where my camera goes online and then it asks me to enter an iot edge connection string, while according to the documentation, I should be receiving an access code and logging into the azure portal. So, I created an iot hub in my subscription, added a device on the iot edge and got the connection string of my added device. So after entering this connection string in the config step, it just doesn't connect to azure and throws this:-
 
![Capture](https://user-images.githubusercontent.com/50492020/106332583-150f5280-6255-11eb-9ac9-d3ea723d11aa.PNG)
" Your camera failed to connect to Microsoft Azure. Please double check you wifi connection and iot edge connection string"

I am not sure if its got to do with firmware not updated. 

The firmware update error:-
The version I am trying to update to is 5370. The adb commands are running fine for me, I am able to list my device. Copied the 2 windows bat files(machine is surface book 2) to the v0.5370_Perf folder.  But the moment I try to run the  FastbootUpgrade_v6_5.bat file, it tries to run adv reboot bootloader and its unable to see an attached device.

![image](https://user-images.githubusercontent.com/50492020/106333046-e776d900-6255-11eb-9030-4fea42352a26.png)

PS: I am able to see the connected device through adb, I get back a response when I ping a website on adb shell. So it doesn't seem to be an internet connectivity issue

**Comment by v-prsasa** [comment]
@mrzutshi Can you try to do factory reset?

**Comment by mrzutshi** [comment]
@v-prsasa I don't see an option to factory reset it as the device hasn't been set up even once yet

**Comment by v-prsasa** [comment]
@mrzutshi Follow this link - https://azure.github.io/Vision-AI-DevKit-Pages/docs/reset/ and try

**Comment by v-iskha** [comment]
@mrzutshi - Did the factory reset resolved the issue for you.

**Comment by v-iskha** [comment]
Closing as there is no response since past 19 days (already sent a reminder question 14 days back).
