### ISSUE TITLE
Please helpme device stopped working after first setup #245

### ISSUE THREAD

**Issue by thinkgandhi** [microsoft/vision-ai-developer-kit#335]
The same issue as #245 appearing to me. I have the latest firmware . I followed exactly as the post suggests. 
I can't even reflash.

**Comment by v-iskha** [comment]
@thinkgandhi - Use this [guide](https://azure.github.io/Vision-AI-DevKit-Pages/docs/reset/) to reset the device. Let us know the outcome.

**Comment by thinkgandhi** [comment]
Even though I followed this guide yesterday, I couldn't able to fix it. This morning with fresh mind I started . Voila. Worked like a charm. But one thing I found is I counted 5 seconds and then I immediately looked at the list of Wifi. Looks like we need to be very quick. One more point , you have to wait for few minutes for http://setupcameraai.ms  to function. So don't rush.
