### ISSUE TITLE
Stuck with 3 solid red lights

### ISSUE THREAD

**Issue by AzureJedi** [microsoft/vision-ai-developer-kit#336]
Hi team,

I've tried to recover from failed flash, fastbootmode flash as well as QFIL flash, all with no success.  When i hard reset the device i get stuck with 3 solid red lights, which after some time look orange.  Any idea what im doing worng and how i can get my device working again.  When i try to flash it it reboots in fastbootmode but then the update stops cos it cant find any devices.

BR,
Karl

**Comment by v-prsasa** [comment]
@AzureJedi Could you please check the battery level of the device? We have observed that when battery level is less 50% we face this kind of issue.

**Comment by AzureJedi** [comment]
adb shell cat /sys/class/power_supply/battery/capacity gives me 74

**Comment by v-prsasa** [comment]
@AzureJedi Can you try to disconnect the device and connect again?

**Comment by AzureJedi** [comment]
Yes i tried that. Lights are constant red

![image](https://user-images.githubusercontent.com/38527352/114393632-83985700-9b9a-11eb-9217-16b3cd352d52.png)

**Comment by v-prsasa** [comment]
@AzureJedi I hope your device is properly connected via USB cable. Are you using latest firmware? If not then please upgrade it by following the steps given in this [link](https://azure.github.io/Vision-AI-DevKit-Pages/docs/Firmware/).

**Comment by AzureJedi** [comment]
The adb tool sees teh device before teh firmware update starts... I've tried several cables with no luck. Im on an old firmware, 0.2...

**Comment by v-prsasa** [comment]
@AzureJedi If you are in old firmware please can you upgrade it to latest one and try again after upgrading.

**Comment by AzureJedi** [comment]
I have tried several times to run the upgrade firmware: 
![image](https://user-images.githubusercontent.com/38527352/114426383-5196ed00-9bba-11eb-95a0-9c6927b1151c.png)
I used shell to see the device and the data directory is 100% full and docker is not starting...

**Comment by AzureJedi** [comment]
Any ideas why the device is not recognised once it goes into fastboot mode?  Is there a way to force a factory reset or for a firmware flash another way?  I can still see the device and adb shell into it.  I managed to get the red lights flashing once but have no idea how i managed.

**Comment by AzureJedi** [comment]
I've managed to get 3 flashing amber, and access to wifi. But the portal is not loading... to setup the device... Still no luck with the firmware.  if i adb shell into the device I cannot see if docker is running.  I get an error that there is no space left on the device?
![image](https://user-images.githubusercontent.com/38527352/114732079-8766dd80-9d42-11eb-9b39-3993cb0c1389.png)
![image](https://user-images.githubusercontent.com/38527352/114732187-9baada80-9d42-11eb-9536-a0be6df15bf0.png)

**Comment by v-prsasa** [comment]
@AzureJedi To access the portal you have t be in your network not in wifi.

**Comment by AzureJedi** [comment]
I followed these steps: 
From your PC, connect to a Wi-Fi network named MSIOT_xxxxxx (xxxxxx is the last 6 characters of the device’s Wi-Fi MAC address, e.g. MSIOT_BD097D). That i managed.  now I cannot seem to get the portal to load, the camera has an IP address and i can ping it. 192.168.X.X

**Comment by v-prsasa** [comment]
Resolving as per the below email Confirmation.

From: Karl Davies-Barrett <karldb@microsoft.com> 
Sent: Thursday, April 15, 2021 12:51 AM
To: Priyanka Sasany (MINDTREE LIMITED) <v-prsasa@microsoft.com>
Subject: Re: AIVision kit

Managed to get it working... used my mac instead of windows....
Thanks for all your support.
Karl
Get Outlook for Android
