### ISSUE TITLE
I cant choose VAIDK in Coustum Vision. 

### ISSUE THREAD

**Issue by Justusjulius** [microsoft/vision-ai-developer-kit#339]
I would like to choose VAIDK to import in to my Camera. But this is not possible for me. Is the Camera not supported?

**Comment by mimcco** [comment]
Hi @Justusjulius, unfortunately support for the VAIDK is limited and we can no longer guarantee it will remain compatible with services such as Custom Vision as it gets updated. VAIDK should no longer be an import option in Custom Vision.
