### ISSUE TITLE
BUG: Firmware update source 

### ISSUE THREAD

**Issue by sadhoss** [microsoft/vision-ai-developer-kit#364]
When trying to download the firmware update from [altek](https://store.altek.com.tw/downloads/Azure-IoT-Starter-Kit), I am requested to sign in with a Microsoft account. Post sign in, I am presented with a prompt message saying the file is not available, or that I do not have access to it.

Is this the only source for a firmware update on the VAIDK or is there other sources?

**Comment by V4A001** [comment]
I have same issue.

**Comment by greeksy** [comment]
I have the same issue.. has anyone figured anything out yet?

**Comment by greeksy** [comment]
I have been in contact with Olivier Bloch and Altek has now fixed the firmware update and it is ready for download! Thank you Olivier!

**Comment by sadhoss** [comment]
Awesome @greeksy! Thanks!
