### ISSUE TITLE
Preserve the device OOBE and all other settings after firmware update

### ISSUE THREAD

**Issue by initmahesh** [microsoft/vision-ai-developer-kit#75]
after each firmware udpate the user need to go through OOBE and will loose all other settings , please provide a wayt o update firmware same as ubuntu does today ...

**Comment by Devinwong** [comment]
The current firmware flash methodology is provided by Qualcomm and is a clean flash. That means we are not able to preserve anything, by design. This request won't be able to implement before Over-The-Air update feature is done.

**Comment by v-prsasa** [comment]
@Devinwong Any update on this?

**Comment by v-prsasa** [comment]
@Devinwong Any update on this?

**Comment by v-iskha** [comment]
Under consideration for future updates.
