### ISSUE TITLE
Get started module should report back its ProductInfo to capture telemetry

### ISSUE THREAD

**Issue by ebertrams** [microsoft/vision-ai-developer-kit#91]
Set this "ProductInfo" tag to value "microsoft_iot.edge-ai-vision-dev-kit-get-started-container" using the methods defined here: https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/Iothub_sdk_options.md

**Comment by jkubicka** [comment]
@ancaantochi Any update on this one?

**Comment by jkubicka** [comment]
Closing - please re-open if still an issue. Thanks.
