### ISSUE TITLE
Feature Request: How to display my text out the HDMI

### ISSUE THREAD

**Issue by ksaye** [microsoft/vision-ai-developer-kit#96]
My goal is to show more than just the label, but to show FPS or the like.  I do not see the ability to write to the screen.

**Comment by v-prsasa** [comment]
@naivelogic Any update on this?

**Comment by PuneetRahejaMS** [comment]
@ksaye Revisiting this old thread. Do you need further support on this?

**Comment by v-iskha** [comment]
Under consideration for future updates.
